better error message if composer.lock is garbage

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -153,6 +153,8 @@ foreach($argv as $repo) $repositories[] = ["type" => "composer", "url" => $repo]
 $have_runtime_req = false;
 if(file_exists(getenv("COMPOSER_LOCK"))) {
     $lock = json_decode(file_get_contents(getenv("COMPOSER_LOCK")), true);
+    // basic lock file validity check
+    if(!$lock || !isset($lock["platform"], $lock["packages"])) exit(1);
     // our main require will be what is in the lock "platform" key
     $have_runtime_req |= hasreq($lock["platform"]);
     $require = mkreq(array_filter($lock["platform"], $preqfilter, ARRAY_FILTER_USE_KEY));
@@ -191,8 +193,9 @@ $json = [
     "require" => $require,
 ];
 echo json_encode($json);
-' -- "$BP_DIR/support/installer/" "$S3_URL" 2>&1 >$BUILD_DIR/.heroku/php/composer.json | indent || error "Couldn't parse '$COMPOSER_LOCK'; it must be valid JSON.
-Run 'composer update' to have it re-generated by Composer."
+' -- "$BP_DIR/support/installer/" "$S3_URL" 2>&1 >$BUILD_DIR/.heroku/php/composer.json | indent || error "Couldn't parse '$COMPOSER_LOCK'; it must be a valid lock
+file generated by Composer. Run 'composer update', add/commit
+the change, then push again."
 
 if composer install -d "$BUILD_DIR/.heroku/php" --no-dev 2>&1 | tee $BUILD_DIR/.heroku/php/install.log | grep --line-buffered '  - Installing heroku-sys/' | sed -u 's/  - Installing heroku-sys\//- /' | indent; then
     :
