improve wording for failed system install errors

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -186,22 +186,26 @@ Run 'composer update' to have it re-generated by Composer."
 if composer install -d "$BUILD_DIR/.heroku/php" --no-dev 2>&1 | tee $BUILD_DIR/.heroku/php/install.log | grep --line-buffered '  - Installing heroku-sys/' | sed -u 's/  - Installing heroku-sys\//- /' | indent; then
     :
 else
-    error "Failed to install system dependencies.
-Your requirements could not be resolved to a set of dependencies,
-or a repository was unreachable. Full progress output follows:
+    error "Failed to install system packages.
 
-$(cat $BUILD_DIR/.heroku/php/install.log | sed -e 's/heroku-sys\///g' -e 's/Loading composer repositories/Loading repositories/' -e 's/^/> /')
+Your platform requirements (for runtimes and extensions) could
+not be resolved to an installable set of dependencies, or a
+repository was unreachable.
 
-The following runtimes are currently available:
+Full error information from installation attempt:
 
-PHP $(composer show -d "$BUILD_DIR/.heroku/php" --available heroku-sys/php 2>&1 | grep versions | fold -s -w 60 || true)
-HHVM $(composer show -d "$BUILD_DIR/.heroku/php" --available heroku-sys/hhvm 2>&1 | grep versions | fold -s -w 60 || true)
+$(cat $BUILD_DIR/.heroku/php/install.log | sed -e 's/heroku-sys\///g' -e 's/^Loading composer repositories with package information/Loading repositories with available runtimes and extensions/' -e 's/^Installing dependencies.*//' -e '/^Potential causes:/,$d' -e 's/^/> /')
 
-Please verify that your '$COMPOSER_LOCK' requirements are matching
-the versions above and that any required extensions are available
-for the versions you intend to use.
+Please verify that all requirements for runtime versions in
+'$COMPOSER_LOCK' are compatible with the list below, and ensure
+all required extensions are available for the desired runtimes.
 
-For a list of supported runtimes and extensions on Heroku, please
+For reference, the following runtimes are currently available:
+
+PHP:  $(composer show -d "$BUILD_DIR/.heroku/php" --available heroku-sys/php 2>&1 | sed -n 's/^versions : //p' | fold -s -w 58 || true)
+HHVM: $(composer show -d "$BUILD_DIR/.heroku/php" --available heroku-sys/hhvm 2>&1 | sed -n 's/^versions : //p' | fold -s -w 58 || true)
+
+For a list of supported runtimes & extensions on Heroku, please
 refer to: https://devcenter.heroku.com/articles/php-support"
 fi
 
