support custom name for composer.json via $COMPOSER env var if it exists

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -71,18 +71,26 @@ RTVS_URL="https://php-runtime-version-selector.herokuapp.com"
 
 cd $BUILD_DIR
 
-if [[ -s "composer.json" ]]; then
-    cat composer.json | python -mjson.tool &> /dev/null || error "Could not parse composer.json; make sure it's valid!"
+if [[ -n ${COMPOSER:-} ]]; then
+    status "Using '$COMPOSER' (from "'$COMPOSER env var) for installation.'
 else
-    if [[ ! -f "composer.json" ]]; then
-        warning 'No composer.json found.
-Using index.php to declare PHP applications is considered legacy
-functionality and may lead to unexpected behavior.'
+    export COMPOSER="composer.json"
+fi
+COMPOSER_LOCK=$(basename "$COMPOSER" ".json")".lock" # replace .json with .lock if it exists, append .lock otherwise
+
+
+if [[ -s "$COMPOSER" ]]; then
+    cat "$COMPOSER" | python -mjson.tool &> /dev/null || error "Could not parse '$COMPOSER'; make sure it's valid!"
+else
+    if [[ ! -f "$COMPOSER" ]]; then
+        warning "No '$COMPOSER' found.
+Using 'index.php' to declare PHP applications is considered legacy
+functionality and may lead to unexpected behavior."
     else
-        notice 'Your composer.json is completely empty.
-Please change its contents to at least "{}" so it is valid JSON.'
+        notice "Your '$COMPOSER' is completely empty.
+Please change its contents to at least '{}' so it is valid JSON."
     fi
-    echo "{}" > composer.json
+    echo "{}" > $COMPOSER
 fi
 
 mkdir -p .heroku/php
@@ -99,11 +107,11 @@ else
 fi
 engine="php"
 engine_r="php -r"
-if [[ -f "composer.json" ]]; then
-    if [[ ! -f "composer.lock" ]]; then
-        cat composer.json | python -c 'import sys, json; sys.exit(json.load(sys.stdin).get("require", {}))' 2> /dev/null || error "Your 'composer.json' lists dependencies inside 'require',
-but no 'composer.lock' was found. Please run 'composer update' to
-re-generate 'composer.lock' if necessary, and commit it into your
+if [[ -f "$COMPOSER" ]]; then
+    if [[ ! -f "$COMPOSER_LOCK" ]]; then
+        cat composer.json | python -c 'import sys, json; sys.exit(json.load(sys.stdin).get("require", {}))' 2> /dev/null || error "Your '$COMPOSER lists dependencies inside 'require',
+but no '$COMPOSER_LOCK' was found. Please run 'composer update' to
+re-generate '$COMPOSER_LOCK' if necessary, and commit it into your
 repository. For more information, please refer to the docs at
 https://devcenter.heroku.com/articles/php-support#activation"
     fi
@@ -113,13 +121,13 @@ import sys, json
 ret = {}
 ret["packages"] = sys.stdin.read().splitlines()
 try:
-    c_lock = json.load(open("composer.lock"))
+    c_lock = json.load(open(sys.argv[1]))
     ret["lock"] = {k: c_lock.get(k, None) for k in ["minimum-stability", "prefer-stable", "stability-flags"]}
     ret["lock"]["platform"] = {k: dict(c_lock.get("platform", {})).get(k, None) for k in ["php", "hhvm"]} # wrap in dict() to prevent simple errors with {} vs []
 except IOError:
     ret["lock"] = None
 print json.dumps(ret)
-' 2> /dev/null) || error "Couldn't parse composer.lock; it must be valid JSON.
+' "$COMPOSER_LOCK" 2> /dev/null) || error "Couldn't parse '$COMPOSER_LOCK'; it must be valid JSON.
 Run 'composer update' to have it re-generated by Composer."
 
     # warn if minimum-stability is set to non-stable (regardless of whether prefer-stable is used)
@@ -135,17 +143,26 @@ see https://getcomposer.org/doc/01-basic-usage.md#stability"
     solver_result=$(echo -n "$solver_payload" | curl --silent --location --fail -H'Content-Type: application/json' -H"X-Build-Request-Id: ${REQUEST_ID:-}" -d @- "${RTVS_URL}/resolve?default_runtime=php") || error "Failed to resolve runtime requirements.
 If the issue persists, please contact support."
     while IFS="|" read runtime_name runtime_source runtime_constraint runtime_result; do
+        # make sure we use the correct names for "composer.json" and "composer.lock"
+        case "$runtime_source" in
+            "composer.json")
+                runtime_source="$COMPOSER"
+                ;;
+            "composer.lock")
+                runtime_source="$COMPOSER_LOCK"
+                ;;
+        esac
         if [[ $runtime_result ]]; then
             if [[ $runtime_source == "default" ]]; then
-                status "No runtime required in composer.json, defaulting to ${runtime_name^^} $runtime_result."
+                status "No runtime required in '$COMPOSER', defaulting to ${runtime_name^^} $runtime_result."
             else
-                status "Resolved $runtime_source requirement for ${runtime_name^^} to version ${runtime_result}."
+                status "Resolved '$runtime_source' requirement for ${runtime_name^^} to version ${runtime_result}."
                 if [[ "$runtime_constraint" == "$runtime_result" || "$runtime_constraint" == "=$runtime_result" ]]; then
                     recommended_selector="~$runtime_result"
                     if [[ $runtime_name == "hhvm" ]]; then
                         recommended_selector="${recommended_selector%.*}" # strip "3.2.0" to just "3.2"; HHVM has different versioning
                     fi
-                    warning "Your composer.json requirement for runtime '$runtime_name'
+                    warning "Your '$COMPOSER' requirement for runtime '$runtime_name'
 specifies an exact-match constraint of '$runtime_constraint'.
 This means you will not automatically get more recent compatible
 versions of ${runtime_name^^} on push once they are available. As any such
@@ -168,7 +185,7 @@ see https://devcenter.heroku.com/articles/cedar-14-migration"
                 fi
             fi
         else
-            error "Could not resolve $runtime_source requirement for ${runtime_name^^} $runtime_constraint,
+            error "Could not resolve '$runtime_source' requirement for ${runtime_name^^} $runtime_constraint,
 please adjust the selector. The following runtimes are available:
 $(echo $runtimes | fold -s -w 65)"
         fi
@@ -240,12 +257,12 @@ if [[ "${PHP_VERSION}" ]]; then
     }
     
     exts=()
-    if [[ -f "composer.lock" ]]; then
-        exts=($(cat composer.lock | python -c 'import sys, json, itertools; l=json.load(sys.stdin); print "\n".join(list(set(itertools.chain([plat[4:].lower() for plat in l.get("platform", []) if plat.startswith("ext-")], *[ [ pkg[4:].lower() for pkg in p.get("require", []) if pkg.startswith("ext-") ] for p in l.get("packages", []) ]))))' 2> /dev/null || true)) # convert to array
-        ext_source="composer.lock"
+    if [[ -f "$COMPOSER_LOCK" ]]; then
+        exts=($(cat "$COMPOSER_LOCK" | python -c 'import sys, json, itertools; l=json.load(sys.stdin); print "\n".join(list(set(itertools.chain([plat[4:].lower() for plat in l.get("platform", []) if plat.startswith("ext-")], *[ [ pkg[4:].lower() for pkg in p.get("require", []) if pkg.startswith("ext-") ] for p in l.get("packages", []) ]))))' 2> /dev/null || true)) # convert to array
+        ext_source="$COMPOSER_LOCK"
     else
-        exts=($(cat composer.json | python -c 'from __future__ import print_function; import sys, json; { print(key[4:].lower()) for key in json.load(sys.stdin)["require"] if key.startswith("ext-")}' 2> /dev/null || true)) # convert to array
-        ext_source="composer.json"
+        exts=($(cat "$COMPOSER" | python -c 'from __future__ import print_function; import sys, json; { print(key[4:].lower()) for key in json.load(sys.stdin)["require"] if key.startswith("ext-")}' 2> /dev/null || true)) # convert to array
+        ext_source="$COMPOSER"
     fi
     for ext in "${!exts[@]}"; do # loop over keys in case the array is empty or else it'll error out
         install_ext "${exts[$ext]}" $ext_source
@@ -290,7 +307,7 @@ composer --version 2> /dev/null | tail -n 1 | indent
 if [[ -e "$(composer config vendor-dir 2> /dev/null | tail -n 1)" ]]; then # tail, as composer echos outdated version warnings to STDOUT
     warning "Your Composer vendor dir is part of your Git repository.
 That directory should not be under version control; only your
-'composer.json' and 'composer.lock' files should be added, which
+'$COMPOSER' and '$COMPOSER_LOCK' files should be added, which
 will let Composer handle installation of dependencies on deploy.
 To suppress this notice, first remove the folder from your index
 by running 'git rm --cached $(composer config vendor-dir 2> /dev/null | tail -n 1)/'.
@@ -322,12 +339,12 @@ fi
 unset COMPOSER_GITHUB_OAUTH_TOKEN
 
 # install dependencies unless composer.json is completely empty (in which case it'd talk to packagist.org which may be slow and is unnecessary)
-cat composer.json | python -c 'import sys,json; sys.exit(not json.load(sys.stdin));' && composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction 2>&1 | indent
+cat "$COMPOSER" | python -c 'import sys,json; sys.exit(not json.load(sys.stdin));' && composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction 2>&1 | indent
 
-composer show --installed heroku/heroku-buildpack-php &> /dev/null && error "Your composer.json requires 'heroku/heroku-buildpack-php'.
+composer show --installed heroku/heroku-buildpack-php &> /dev/null && error "Your '$COMPOSER' requires 'heroku/heroku-buildpack-php'.
 This package may only be used as a dependency in 'require-dev'!"
 
-if cat composer.json | python -c 'import sys,json; sys.exit("compile" not in json.load(sys.stdin).get("scripts", {}));'; then
+if cat "$COMPOSER" | python -c 'import sys,json; sys.exit("compile" not in json.load(sys.stdin).get("scripts", {}));'; then
     status "Running 'composer compile'..."
     composer run-script --no-dev --no-interaction compile 2>&1 | indent
 fi
