cut messages to max length of 65 to take HTTPS Git's 'remote: ' prefix into account

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -97,8 +97,8 @@ engine="php"
 engine_r="php -r"
 if [[ -f "composer.json" ]]; then
     if [[ ! -f "composer.lock" ]]; then
-        cat composer.json | python -c 'import sys, json; print sys.exit(any(key.count("/") for key in json.load(sys.stdin).get("require", {})))' 2> /dev/null || error "Your composer.json specifies dependencies, but no composer.lock
-was found, please check it into your repository along with composer.json!"
+        cat composer.json | python -c 'import sys, json; print sys.exit(any(key.count("/") for key in json.load(sys.stdin).get("require", {})))' 2> /dev/null || error "Your composer.json has dependencies, but no composer.lock
+was found, check it into your repository alongside composer.json!"
     fi
     
     solver_payload=$(echo -n "$runtimes" | python -c '
@@ -115,27 +115,28 @@ try:
 except IOError:
     ret["lock"] = None
 print json.dumps(ret)
-' 2> /dev/null) || error "Couldn't parse composer.lock; it must be non-empty and valid JSON.
-Run 'composer update' to have it re-generated or removed by Composer."
+' 2> /dev/null) || error "Couldn't parse composer.lock; it must be valid JSON.
+Run 'composer update' to have it re-generated by Composer."
     solver_result=$(echo -n "$solver_payload" | curl --silent --location --fail -H'Content-Type: application/json' -d @- "${RTVS_URL}/resolve?default_runtime=php") || error "Failed to resolve runtime requirements.
 If the issue persists, please contact support."
     while IFS="|" read runtime_name runtime_source runtime_constraint runtime_result; do
         if [[ $runtime_result ]]; then
             if [[ $runtime_source == "default" ]]; then
-                status "No runtime requirements in composer.json, defaulting to ${runtime_name^^} $runtime_result."
+                status "No runtime required in composer.json, defaulting to ${runtime_name^^} $runtime_result."
             else
-                status "Resolved $runtime_source requirement for ${runtime_name^^} $runtime_constraint to version $runtime_result."
+                status "Resolved $runtime_source requirement for ${runtime_name^^} to version ${runtime_result}."
                 if [[ "$runtime_constraint" == "$runtime_result" || "$runtime_constraint" == "=$runtime_result" ]]; then
                     recommended_selector="~$runtime_result"
                     if [[ $runtime_name == "hhvm" ]]; then
                         recommended_selector="${recommended_selector%.*}" # strip "3.2.0" to just "3.2"; HHVM has different versioning
                     fi
-                    warning "Your composer.json requires version '$runtime_constraint' for runtime '$runtime_name'.
-This exact-match version constraint means you will not automatically get
-more recent compatible versions of ${runtime_name^^} on push once they are released.
-Such new versions may contain security updates, so we strongly suggest
+                    warning "Your composer.json requirement for runtime '$runtime_name'
+specifies an exact-match constraint of '$runtime_constraint'.
+This means you will not automatically get more recent compatible
+versions of ${runtime_name^^} on push once they are available. As any such
+new version may contain security updates, we strongly suggest
 you use a more lenient selector like '$recommended_selector' instead.
-See https://devcenter.heroku.com/articles/php-support for more details."
+See https://devcenter.heroku.com/articles/php-support for info."
                 fi
             fi
             if [[ $runtime_name == "php" ]]; then
@@ -145,16 +146,16 @@ See https://devcenter.heroku.com/articles/php-support for more details."
                 engine="hhvm"
                 engine_r="hhvm --php -r"
                 if [[ "$STACK" == "cedar" ]]; then
-                    notice_inline "Support for HHVM on the cedar stack is deprecated and will be
-removed soon. Please upgrade to cedar-14 to continue using HHVM and get
-access to new releases. For more information on migrating to cedar-14,
-please refer to https://devcenter.heroku.com/articles/cedar-14-migration"
+                    notice_inline "Support for HHVM on the cedar stack is deprecated and
+will be removed soon. Please upgrade to cedar-14 to continue to
+use HHVM and get access to new releases. For more information,
+see https://devcenter.heroku.com/articles/cedar-14-migration"
                 fi
             fi
         else
             error "Could not resolve $runtime_source requirement for ${runtime_name^^} $runtime_constraint,
-please adjust the version selector. The following runtimes are available:
-$(echo $runtimes | fold -s -w 73)"
+please adjust the selector. The following runtimes are available:
+$(echo $runtimes | fold -s -w 65)"
         fi
     done <<<"$solver_result"
 fi
@@ -250,14 +251,14 @@ status "Installing dependencies..."
 
 # check if we should use a composer.phar version bundled with the project
 if [[ -f "composer.phar" ]]; then
-    [[ -x "composer.phar" ]] || error "composer.phar in root directory is not executable; 'chmod a+x' it!"
+    [[ -x "composer.phar" ]] || error "File '/composer.phar' isn't executable; please 'chmod +x'!"
     $engine_r 'new Phar("composer.phar");' &> /dev/null || error "File '/composer.phar' is not a valid PHAR archive!"
     composer() {
         $engine composer.phar "$@"
     }
     export -f composer
-    composer --version 2>&1 | grep "^Composer version" > /dev/null || error "composer.phar in root directory doesn't seem to contain Composer!"
-    notice_inline "Using custom composer.phar (in root dir) to install dependencies."
+    composer --version 2>&1 | grep "^Composer version" > /dev/null || error "File '/composer.phar' is not a Composer executable!"
+    notice_inline "Using '/composer.phar' to install dependencies."
 else
     curl --silent --location "$S3_URL/composer.tar.gz" | tar xz -C $BUILD_DIR/.heroku/php
     composer() {
@@ -271,12 +272,15 @@ composer --version 2> /dev/null | tail -n 1 | indent
 
 # throw a notice if people have added their vendor dir to Git; that's bad practice and makes everything slow and cluttered
 if [[ -e "$(composer config vendor-dir)" ]]; then
-    warning "You have put Composer's vendor directory under version control.
-That directory should not be in your Git repository; only composer.json
-and composer.lock should be added, with Composer handling installation.
-Please 'git rm --cached $(composer config vendor-dir)/' to remove the folder from your index,
-then add '/$(composer config vendor-dir)/' to your '.gitignore' list to remove this notice.
-For more information, refer to the Composer FAQ: http://bit.ly/1rlCSZU"
+    warning "Your Composer vendor dir is part of your Git repository.
+That directory should not be under version control; only your
+'composer.json' and 'composer.lock' files should be added, which
+will let Composer handle installation of dependencies on deploy.
+To suppress this notice, first remove the folder from your index
+by running 'git rm --cached $(composer config vendor-dir)/'.
+Next, edit your project's '.gitignore' file and add the folder
+'/$(composer config vendor-dir)/' to the list.
+For more info, refer to the Composer FAQ: http://bit.ly/1rlCSZU"
 fi
 
 # handle custom oauth keys
@@ -284,17 +288,17 @@ COMPOSER_GITHUB_OAUTH_TOKEN=${COMPOSER_GITHUB_OAUTH_TOKEN:-}
 if [[ -n "$COMPOSER_GITHUB_OAUTH_TOKEN" ]]; then
     if curl --fail --silent -H "Authorization: token $COMPOSER_GITHUB_OAUTH_TOKEN" https://api.github.com/rate_limit > /dev/null; then
         composer config -g github-oauth.github.com "$COMPOSER_GITHUB_OAUTH_TOKEN" &> /dev/null # redirect outdated version warnings (Composer sends those to STDOUT instead of STDERR)
-        notice_inline 'Using custom GitHub OAuth token in $COMPOSER_GITHUB_OAUTH_TOKEN'
+        notice_inline 'Using $COMPOSER_GITHUB_OAUTH_TOKEN for GitHub OAuth.'
     else
-        error 'Invalid GitHub OAuth token in $COMPOSER_GITHUB_OAUTH_TOKEN'
+        error 'Invalid $COMPOSER_GITHUB_OAUTH_TOKEN for GitHub OAuth!'
     fi
 else
     # don't forget to remove any stored key if it's gone from the env
     composer config -g --unset github-oauth.github.com &> /dev/null # redirect outdated version warnings (Composer sends those to STDOUT instead of STDERR)
     if curl --silent https://api.github.com/rate_limit | python -c 'import sys, json; sys.exit((json.load(sys.stdin)["resources"]["core"]["remaining"] > 0))'; then # yes, check > 0, not < 1 - exit status of 0 will trigger the if
         notice "You've reached the GitHub API's request rate limit.
-Composer will now try and fall back to slower downloads from source.
-It's strongly recommended you use a custom OAuth token; for details, see
+Composer will try and fall back to slower downloads from source.
+It's strongly recommended you use a custom OAuth token; see
 http://devcenter.heroku.com/articles/php-support#custom-github-oauth-tokens"
     fi
 fi
@@ -304,8 +308,8 @@ unset COMPOSER_GITHUB_OAUTH_TOKEN
 # install dependencies
 composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction | indent
 
-composer show --installed heroku/heroku-buildpack-php &> /dev/null && error "Your composer.json requires package 'heroku/heroku-buildpack-php'.
-This package may only be used as a dev dependency (in 'require-dev')!"
+composer show --installed heroku/heroku-buildpack-php &> /dev/null && error "Your composer.json requires 'heroku/heroku-buildpack-php'.
+This package may only be used as a dependency in 'require-dev'!"
 
 status "Preparing runtime environment..."
 
@@ -367,5 +371,5 @@ install_blackfire_agent
 if [[ ! -f "Procfile" ]]; then
     bindir=$(composer config bin-dir 2> /dev/null | tail -n 1) # tail, as composer echos outdated version warnings to STDOUT
     echo "web: $bindir/heroku-$engine-apache2" > Procfile
-    notice_inline "No Procfile, defaulting to 'web: $bindir/heroku-$engine-apache2'"
+    notice_inline "No Procfile, using 'web: $bindir/heroku-$engine-apache2'."
 fi
