support custom platform repositories

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -53,15 +53,6 @@ unset GIT_DIR
 
 export_env_dir "$env_dir" '^[A-Z_][A-Z0-9_]*$' '^(HOME|PATH|GIT_DIR|CPATH|CPPATH|LD_PRELOAD|LIBRARY_PATH|LD_LIBRARY_PATH|STACK|REQUEST_ID)$'
 
-BUILDPACK_URL=${BUILDPACK_URL:-} # Anvil has none
-buildpack_branch=$(expr "$BUILDPACK_URL" : '^.*/heroku-buildpack-php#\(..*\)$' || expr "$BUILDPACK_URL" : '^.*/heroku-buildpack-php\.git#\(..*\)$' || true) # POSIX expr doesn't understand ".+" or "(\.git)?"
-buildpack_branch=${buildpack_branch:-master}
-
-if [[ "$buildpack_branch" != v* && "$buildpack_branch" != "master" ]]; then
-    s3_url="develop"
-fi
-s3_url="https://lang-php.s3.amazonaws.com/dist-${STACK}-${s3_url:-"master"}"
-
 cd $build_dir
 
 if [[ -n ${COMPOSER:-} ]]; then
@@ -119,17 +110,28 @@ export PATH=/app/.heroku/php/bin:$PATH
 
 status "Bootstrapping..."
 
+s3_url="https://lang-php.s3.amazonaws.com/dist-${STACK}-master/"
+
 # minimal PHP needed for installs, and make "composer" invocations use that for now
 mkdir -p $build_dir/.heroku/php-min
 ln -s $build_dir/.heroku/php-min /app/.heroku/php-min
-curl --silent --location "$s3_url/php-min.tar.gz" | tar xz -C $build_dir/.heroku/php-min
-curl --silent --location "$s3_url/composer-1.0.0alpha11.tar.gz" | tar xz -C $build_dir/.heroku/php
+curl --silent --location "${s3_url}php-min.tar.gz" | tar xz -C $build_dir/.heroku/php-min
+curl --silent --location "${s3_url}composer-1.0.0alpha11.tar.gz" | tar xz -C $build_dir/.heroku/php
 composer() {
     /app/.heroku/php-min/bin/php $(which composer) "$@"
 }
 export -f composer
 
-status "Installing system packages..."
+# prepend the default repo to the list configured by the user
+# list of repositories to use is in ascening order of precedence
+HEROKU_PHP_PLATFORM_REPOSITORIES="${s3_url} ${HEROKU_PHP_PLATFORM_REPOSITORIES:-}"
+if [[ "${HEROKU_PHP_PLATFORM_REPOSITORIES}" == *" - "* ]]; then
+	# a single "-" in the user supplied string removes everything to the left of it; can be used to delete the default repo
+	notice_inline "Default platform repository disabled."
+	HEROKU_PHP_PLATFORM_REPOSITORIES=${HEROKU_PHP_PLATFORM_REPOSITORIES#*" - "}
+fi
+
+status "Installing platform packages..."
 
 # extract requirements from composer.lock
 /app/.heroku/php-min/bin/php -r '
@@ -147,8 +149,8 @@ $repositories = [
     ["packagist" => false],
     ["type" => "path", "url" => array_shift($argv)],
 ];
-// all other args are repo URLs
-foreach($argv as $repo) $repositories[] = ["type" => "composer", "url" => $repo];
+// all other args are repo URLs; they get passed in ascending order of precedence, so we reverse
+foreach(array_reverse($argv) as $repo) $repositories[] = ["type" => "composer", "url" => $repo];
 
 $have_runtime_req = false;
 if(file_exists(getenv("COMPOSER_LOCK"))) {
@@ -193,7 +195,7 @@ $json = [
     "require" => $require,
 ];
 echo json_encode($json);
-' -- "$bp_dir/support/installer/" "$s3_url" 2>&1 >$build_dir/.heroku/php/composer.json | indent || error "Couldn't parse '$COMPOSER_LOCK'; it must be a valid lock
+' -- "$bp_dir/support/installer/" $HEROKU_PHP_PLATFORM_REPOSITORIES 2>&1 >$build_dir/.heroku/php/composer.json | indent || error "Couldn't parse '$COMPOSER_LOCK'; it must be a valid lock
 file generated by Composer. Run 'composer update', add/commit
 the change, then push again."
 
@@ -248,7 +250,7 @@ elif composer show -d "$build_dir/.heroku/php" --installed --quiet heroku-sys/hh
 fi
 
 apache_version="2.4.16"
-apache_dist_url="$s3_url/apache-$apache_version.tar.gz"
+apache_dist_url="${s3_url}apache-$apache_version.tar.gz"
 echo "- Apache ($apache_version)" | indent
 curl --silent --location "$apache_dist_url" | tar xz -C $build_dir/.heroku/php
 # Apache; copy in our config
@@ -258,7 +260,7 @@ mkdir -p $build_dir/.heroku/php/.versions/apache2
 echo $apache_version > $build_dir/.heroku/php/.versions/apache2/apache2
 
 nginx_version="1.8.0"
-nginx_dist_url="$s3_url/nginx-$nginx_version.tar.gz"
+nginx_dist_url="${s3_url}nginx-$nginx_version.tar.gz"
 echo "- Nginx ($nginx_version)" | indent
 curl --silent --location "$nginx_dist_url" | tar xz -C $build_dir/.heroku/php
 # nginx; copy in our config
