clean up and simplify some error handling

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -57,23 +57,17 @@ S3_URL="https://lang-php.s3.amazonaws.com/dist-${STACK}-${S3_URL}"
 
 cd $BUILD_DIR
 
-json_empty=true
 if [[ -s "composer.json" ]]; then
-    json_empty=false
-    json_invalid=false
-    cat composer.json | python -mjson.tool &> /dev/null || json_invalid=true
-    if [[ $json_invalid == true ]]; then
-        error "Could not parse composer.json; make sure it's valid!"
-    fi
-elif [[ ! -f "composer.json" ]]; then
-    warning 'No composer.json found.
+    cat composer.json | python -mjson.tool &> /dev/null || error "Could not parse composer.json; make sure it's valid!"
+else
+    if [[ ! -f "composer.json" ]]; then
+        warning 'No composer.json found.
 Using index.php to declare PHP applications is considered legacy
 functionality and may lead to unexpected behavior.'
-else
-    notice 'Your composer.json is completely empty.
-Consider putting at least "{}" in there to make it valid JSON.'
-fi
-if [[ $json_empty == true ]]; then
+    else
+        notice 'Your composer.json is completely empty.
+Please change its contents to at least "{}" so it is valid JSON.'
+    fi
     echo "{}" > composer.json
 fi
 
@@ -92,11 +86,8 @@ fi
 engine="php"
 if [[ -f "composer.json" ]]; then
     if [[ ! -f "composer.lock" ]]; then
-        has_packages=$(cat composer.json | python -c 'import sys, json; print any(key.count("/") for key in json.load(sys.stdin)["require"])' 2> /dev/null || true) # might fail, set -e would stop execution
-        if [ "$has_packages" == "True" ]; then
-            error "Your composer.json specifies dependencies, but no composer.lock
+        cat composer.json | python -c 'import sys, json; print sys.exit(any(key.count("/") for key in json.load(sys.stdin)["require"]))' 2> /dev/null || error "Your composer.json specifies dependencies, but no composer.lock
 was found, please check it into your repository along with composer.json!"
-        fi
     fi
     
     solver_payload=$(echo -n "$runtimes" | python -c '
