log failure and warning counts

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -16,8 +16,17 @@ mkdir -p "$cache_dir"
 env_dir=${3:-} # Anvil has none
 bp_dir=$(cd $(dirname $0); cd ..; pwd)
 
+export BPLOG_PREFIX="buildpack.php"
+export BUILDPACK_LOG_FILE=${BUILDPACK_LOG_FILE:-/dev/null}
+
 # convenience functions
 source $bp_dir/bin/util/common.sh
+
+# stdlib
+source /dev/stdin <<< "$(curl_retry_on_18 --silent https://lang-common.s3.amazonaws.com/buildpack-stdlib/v8/stdlib.sh)"
+
+# failure counting
+source $bp_dir/bin/util/failures.sh
 
 # for extensions that need special treatment
 source $bp_dir/bin/util/newrelic.sh
@@ -38,34 +47,48 @@ export COMPOSER_LOCK=$(basename "$COMPOSER" ".json")".lock" # replace .json with
 
 # a bunch of sanity checks first
 if [[ -s "$COMPOSER" ]]; then
-	cat "$COMPOSER" | python -mjson.tool &> /dev/null || error "Could not parse '$COMPOSER'; make sure it's valid!"
+	cat "$COMPOSER" | python -mjson.tool &> /dev/null || {
+		mcount "failures.composer_json.lint"
+		error "Could not parse '$COMPOSER'; make sure it's valid!"
+	}
 	if [[ ! -f "$COMPOSER_LOCK" ]]; then
-		cat "$COMPOSER" | python -c 'import sys, json; sys.exit(bool(json.load(sys.stdin).get("require", {})))' 2> /dev/null || error <<-EOF
-			Your '$COMPOSER' lists dependencies inside 'require',
-			but no '$COMPOSER_LOCK' was found. Please run 'composer update' to
-			re-generate '$COMPOSER_LOCK' if necessary, and commit it into your
-			repository. For more information, please refer to the docs at
-			https://devcenter.heroku.com/articles/php-support#activation
-		EOF
+		cat "$COMPOSER" | python -c 'import sys, json; sys.exit(bool(json.load(sys.stdin).get("require", {})))' 2> /dev/null || {
+			mcount "failures.composer_lock.missing"
+			error <<-EOF
+				Your '$COMPOSER' lists dependencies inside 'require',
+				but no '$COMPOSER_LOCK' was found. Please run 'composer update' to
+				re-generate '$COMPOSER_LOCK' if necessary, and commit it into your
+				repository. For more information, please refer to the docs at
+				https://devcenter.heroku.com/articles/php-support#activation
+			EOF
+		}
 	else
-		cat "$COMPOSER_LOCK" | python -mjson.tool &> /dev/null || error "Could not parse '$COMPOSER_LOCK'; make sure it's valid!"
-		cat "$COMPOSER_LOCK" | python -c 'import sys, json; l = json.load(sys.stdin); sys.exit(not(l["minimum-stability"] == "stable"));' 2> /dev/null || warning <<-EOF
-			Your '$COMPOSER' contains a non-'stable' setting
-			for 'minimum-stability'. This may cause the installation of
-			unstable versions of runtimes and extensions during this deploy.
-			It is recommended that you always use stability flags instead,
-			even if you have 'prefer-stable' enabled. For more information,
-			see https://getcomposer.org/doc/01-basic-usage.md#stability
-		EOF
+		cat "$COMPOSER_LOCK" | python -mjson.tool &> /dev/null || {
+			mcount "failures.composer_lock.lint"
+			error "Could not parse '$COMPOSER_LOCK'; make sure it's valid!"
+		}
+		cat "$COMPOSER_LOCK" | python -c 'import sys, json; l = json.load(sys.stdin); sys.exit(not(l["minimum-stability"] == "stable"));' 2> /dev/null || {
+			mcount "warnings.composer_lock.minimum_stability"
+			warning <<-EOF
+				Your '$COMPOSER' contains a non-'stable' setting
+				for 'minimum-stability'. This may cause the installation of
+				unstable versions of runtimes and extensions during this deploy.
+				It is recommended that you always use stability flags instead,
+				even if you have 'prefer-stable' enabled. For more information,
+				see https://getcomposer.org/doc/01-basic-usage.md#stability
+			EOF
+		}
 	fi
 else
 	if [[ ! -f "$COMPOSER" ]]; then
+		mcount "warnings.composer_json.missing"
 		warning <<-EOF
 			No '$COMPOSER' found.
 			Using 'index.php' to declare app type as PHP is considered legacy
 			functionality and may lead to unexpected behavior.
 		EOF
 	else
+		mcount "warnings.composer_json.empty"
 		notice <<-EOF
 			Your '$COMPOSER' is completely empty.
 			Please change its contents to at least '{}' so it is valid JSON.
@@ -105,17 +128,23 @@ fi
 mkdir -p $build_dir/.heroku/php-min
 ln -s $build_dir/.heroku/php-min /app/.heroku/php-min
 
-curl_retry_on_18 --fail --silent --location -o $build_dir/.heroku/php-min.tar.gz "${s3_url}php-min-7.0.28.tar.gz" || error <<-EOF
-	Failed to download minimal PHP for bootstrapping.
-	Please try again, or contact support if this problem persists.
-EOF
+curl_retry_on_18 --fail --silent --location -o $build_dir/.heroku/php-min.tar.gz "${s3_url}php-min-7.0.28.tar.gz" || {
+	mcount "failures.bootstrap.download.php-min"
+	error <<-EOF
+		Failed to download minimal PHP for bootstrapping.
+		Please try again, or contact support if this problem persists.
+	EOF
+}
 tar xzf $build_dir/.heroku/php-min.tar.gz -C $build_dir/.heroku/php-min
 rm $build_dir/.heroku/php-min.tar.gz
 
-curl_retry_on_18 --fail --silent --location -o $build_dir/.heroku/composer.tar.gz "${s3_url}composer-1.6.3.tar.gz" || error <<-EOF
-	Failed to download Composer.
-	Please try again, or contact support if this problem persists.
-EOF
+curl_retry_on_18 --fail --silent --location -o $build_dir/.heroku/composer.tar.gz "${s3_url}composer-1.6.3.tar.gz" || {
+	mcount "failures.bootstrap.download.composer"
+	error <<-EOF
+		Failed to download Composer.
+		Please try again, or contact support if this problem persists.
+	EOF
+}
 tar xzf $build_dir/.heroku/composer.tar.gz -C $build_dir/.heroku/php
 rm $build_dir/.heroku/composer.tar.gz
 
@@ -139,12 +168,20 @@ echo "export PATH=\$HOME/.heroku/php/bin:\$PATH:\$HOME/$composer_bindir" > $buil
 status "Installing platform packages..."
 
 # extract requirements from composer.lock
-/app/.heroku/php-min/bin/php $bp_dir/bin/util/platform.php "$bp_dir/support/installer/" $HEROKU_PHP_PLATFORM_REPOSITORIES 2>&1 >$build_dir/.heroku/php/composer.json | indent || error <<-EOF
-	Couldn't load '$COMPOSER_LOCK'; it must be a valid lock
-	file generated by Composer and be in a consistent state.
-	Check above for any parse errors and address them if necessary.
-	Run 'composer update', add/commit the change, then push again.
-EOF
+/app/.heroku/php-min/bin/php $bp_dir/bin/util/platform.php "$bp_dir/support/installer/" $HEROKU_PHP_PLATFORM_REPOSITORIES 2>&1 >$build_dir/.heroku/php/composer.json | indent || {
+	code=$?
+	if [[ $code -eq 3 ]]; then
+		mcount "failures.platform.composer_lock.runtime_only_in_dev"
+	else
+		mcount "failures.platform.composer_lock.parse"
+	fi
+	error <<-EOF
+		Couldn't load '$COMPOSER_LOCK'; it must be a valid lock
+		file generated by Composer and be in a consistent state.
+		Check above for any parse errors and address them if necessary.
+		Run 'composer update', add/commit the change, then push again.
+	EOF
+}
 
 # reset COMPOSER for the platform install step
 COMPOSER_bak="$COMPOSER"
@@ -154,9 +191,19 @@ export COMPOSER=composer.json
 # they are also used in later install attempts for add-on extensions (blackfire, newrelic, ...)
 export export_file_path=$bp_dir/export
 export profile_dir_path=$build_dir/.profile.d
-if composer install -d "$build_dir/.heroku/php" ${HEROKU_PHP_INSTALL_DEV-"--no-dev"} 2>&1 | tee $build_dir/.heroku/php/install.log | grep --line-buffered -E '^  - (Instal|Enab)ling heroku-sys/' | sed -u -E -e 's/^  - (Instal|Enab)ling /- /' -e 's/heroku-sys\///g' | indent; then
+# grep and sed in a subshell with || true, or a failing grep match will cause the exit code to be 1 if "composer install" fails with code 2
+if composer install -d "$build_dir/.heroku/php" ${HEROKU_PHP_INSTALL_DEV-"--no-dev"} 2>&1 | tee $build_dir/.heroku/php/install.log | ( grep --line-buffered -E '^  - (Instal|Enab)ling heroku-sys/' | sed -u -E -e 's/^  - (Instal|Enab)ling /- /' -e 's/heroku-sys\///g' || true ) | indent; then
 	:
 else
+	code=$?
+	install_log=$(cat $build_dir/.heroku/php/install.log | sed -e 's/heroku-sys\///g' -e 's/^Loading composer repositories with package information/Loading repositories with available runtimes and extensions/' -e 's/^Installing dependencies.*//' -e '/^Potential causes:/,$d' -e 's/^/> /')
+	if [[ $code -eq 2 ]]; then
+		# dependency solving failed
+		mcount "failures.platform.solving.$(detect_platform_solving_failures <<< "$install_log")"
+	else
+		# something else
+		mcount "failures.platform.install.$(detect_platform_install_failures <<< "$install_log")"
+	fi
 	error <<-EOF
 		Failed to install system packages.
 		
@@ -166,7 +213,7 @@ else
 		
 		Full error information from installation attempt:
 		
-		$(cat $build_dir/.heroku/php/install.log | sed -e 's/heroku-sys\///g' -e 's/^Loading composer repositories with package information/Loading repositories with available runtimes and extensions/' -e 's/^Installing dependencies.*//' -e '/^Potential causes:/,$d' -e 's/^/> /')
+		$install_log
 		
 		Please verify that all requirements for runtime versions in
 		'$COMPOSER_LOCK' are compatible with the list below, and ensure
@@ -194,12 +241,15 @@ fi
 export COMPOSER="$COMPOSER_bak"
 unset COMPOSER_bak
 
-composer validate --no-check-publish --no-check-all --quiet "$COMPOSER" 2>/dev/null || warning <<-EOF
-	Your '$COMPOSER_LOCK' is not up to date with the latest
-	changes in '$COMPOSER'. To ensure you are not getting stale
-	dependencies, run 'composer update' on your machine and commit
-	any changes to Git before pushing again.
-EOF
+composer validate --no-check-publish --no-check-all --quiet "$COMPOSER" 2>/dev/null || {
+	mcount "warnings.composer_lock.outdated"
+	warning <<-EOF
+		Your '$COMPOSER_LOCK' is not up to date with the latest
+		changes in '$COMPOSER'. To ensure you are not getting stale
+		dependencies, run 'composer update' on your machine and commit
+		any changes to Git before pushing again.
+	EOF
+}
 
 # clean up
 rm -rf /app/.heroku/php-min $build_dir/.heroku/php-min
@@ -217,13 +267,22 @@ status "Installing dependencies..."
 
 # check if we should use a composer.phar version bundled with the project
 if [[ -f "composer.phar" ]]; then
-	[[ -x "composer.phar" ]] || error "File '/composer.phar' isn't executable; please 'chmod +x'!"
-	$engine_r 'new Phar("composer.phar");' &> /dev/null || error "File '/composer.phar' is not a valid PHAR archive!"
+	[[ -x "composer.phar" ]] || {
+		mcount "failures.composer_phar.not_executable"
+		error "File '/composer.phar' isn't executable; please 'chmod +x'!"
+	}
+	$engine_r 'new Phar("composer.phar");' &> /dev/null || {
+		mcount "failures.composer_phar.invalid_phar"
+		error "File '/composer.phar' is not a valid PHAR archive!"
+	}
 	composer() {
 		$engine composer.phar "$@"
 	}
 	export -f composer
-	composer --version 2>&1 | grep "^Composer version" > /dev/null || error "File '/composer.phar' is not a Composer executable!"
+	composer --version 2>&1 | grep "^Composer version" > /dev/null || {
+		mcount "failures.composer_phar.not_composer"
+		error "File '/composer.phar' is not a Composer executable!"
+	}
 	notice_inline "Using '/composer.phar' to install dependencies."
 fi
 # echo composer version for info purposes
@@ -242,6 +301,7 @@ if [[ -f "$composer_vendordir/autoload.php" && -d "$composer_vendordir/composer"
 		EOF
 		)
 	fi
+	mcount "warnings.vendor_dir"
 	warning <<-EOF
 		Your Composer vendor dir is part of your Git repository.
 		This directory should not be under version control; only your
@@ -263,6 +323,7 @@ if [[ -n "$COMPOSER_GITHUB_OAUTH_TOKEN" ]]; then
 		composer config -g github-oauth.github.com "$COMPOSER_GITHUB_OAUTH_TOKEN" &> /dev/null # redirect outdated version warnings (Composer sends those to STDOUT instead of STDERR)
 		notice_inline 'Using $COMPOSER_GITHUB_OAUTH_TOKEN for GitHub OAuth.'
 	else
+		mcount "failures.dependencies.auth.COMPOSER_GITHUB_OAUTH_TOKEN"
 		error 'Invalid $COMPOSER_GITHUB_OAUTH_TOKEN for GitHub OAuth!'
 	fi
 else
@@ -273,20 +334,39 @@ fi
 unset COMPOSER_GITHUB_OAUTH_TOKEN
 
 # install dependencies unless composer.json is completely empty (in which case it'd talk to packagist.org which may be slow and is unnecessary)
-export_env_dir "$env_dir" '^[A-Z_][A-Z0-9_]*$' '^(HOME|PATH|GIT_DIR|CPATH|CPPATH|LD_PRELOAD|LIBRARY_PATH|LD_LIBRARY_PATH|STACK|REQUEST_ID|IFS|HEROKU_PHP_INSTALL_DEV)$'
-cat "$COMPOSER" | python -c 'import sys,json; sys.exit(not json.load(sys.stdin));' && composer install ${HEROKU_PHP_INSTALL_DEV-"--no-dev"} --prefer-dist --optimize-autoloader --no-interaction 2>&1 | indent
+export_env_dir "$env_dir" '^[A-Z_][A-Z0-9_]*$' '^(HOME|PATH|GIT_DIR|CPATH|CPPATH|LD_PRELOAD|LIBRARY_PATH|LD_LIBRARY_PATH|STACK|REQUEST_ID|IFS|HEROKU_PHP_INSTALL_DEV|BPLOG_PREFIX|BUILDPACK_LOG_FILE)$'
+if cat "$COMPOSER" | python -c 'import sys,json; sys.exit(not json.load(sys.stdin));'; then
+	install_log=$(mktemp -t heroku-buildpack-php-composer-install-log-XXXX)
+	composer install ${HEROKU_PHP_INSTALL_DEV-"--no-dev"} --prefer-dist --optimize-autoloader --no-interaction 2>&1 | tee "$install_log" | indent || {
+		code=$?
+		if [[ $code -eq 2 ]]; then
+			# dependency solving failed, which should only ever happen if people have platform overrides in their config
+			mcount "failures.dependencies.solving.$(detect_dependencies_solving_failures < "$install_log")"
+		else
+			mcount "failures.dependencies.install.$(detect_dependencies_install_failures < "$install_log")"
+		fi
+		exit $code
+	}
+fi
 
 # only perform the check for buildpack package if we're not running in Heroku CI
 if [[ -z "${HEROKU_PHP_INSTALL_DEV+are-we-running-in-ci}" ]]; then
-	composer show --installed heroku/heroku-buildpack-php &> /dev/null && error <<-EOF
-		Your '$COMPOSER' requires 'heroku/heroku-buildpack-php'.
-		This package may only be used as a dependency in 'require-dev'!
-	EOF
+	composer show --installed heroku/heroku-buildpack-php &> /dev/null && {
+		mcount "failures.dependencies.buildpack_as_dependency"
+		error <<-EOF
+			Your '$COMPOSER' requires 'heroku/heroku-buildpack-php'.
+			This package may only be used as a dependency in 'require-dev'!
+		EOF
+	}
 fi
 
 if cat "$COMPOSER" | python -c 'import sys,json; sys.exit("compile" not in json.load(sys.stdin).get("scripts", {}));'; then
 	status "Running 'composer compile'..."
-	composer run-script ${HEROKU_PHP_INSTALL_DEV-"--no-dev"} --no-interaction compile 2>&1 | indent
+	composer run-script ${HEROKU_PHP_INSTALL_DEV-"--no-dev"} --no-interaction compile 2>&1 | indent || {
+		code=$?
+		mcount "failures.compile_step"
+		exit $code
+	}
 fi
 
 status "Preparing runtime environment..."
