fix "no version selector" notice not always showing up

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -168,7 +168,9 @@ if(file_exists(getenv("COMPOSER_LOCK"))) {
     $repositories[] = ["type" => "package", "package" => $metapaks];
 }
 // if no PHP or HHVM is required anywhere, we need to add something
-if(!$have_runtime_req) $require["heroku-sys/php"] = isset($require["heroku-sys/php-64bit"]) ? $require["heroku-sys/php-64bit"] : "^5.5.17";
+if(!$have_runtime_req) {
+    file_put_contents("php://stderr", "NOTICE: No PHP version required in ".getenv("COMPOSER_LOCK")."; using ". ($require["heroku-sys/php"] = "^5.5.17") . "\n");
+}
 $json = [
     "config" => ["cache-files-ttl" => 0, "discard-changes" => true],
     "minimum-stability" => isset($lock["minimum-stability"]) ? $lock["minimum-stability"] : "stable",
@@ -178,12 +180,8 @@ $json = [
     "require" => $require,
 ];
 echo json_encode($json);
-' -- "$BP_DIR/support/installer/" "$S3_URL" > $BUILD_DIR/.heroku/php/composer.json || error "Couldn't parse '$COMPOSER_LOCK'; it must be valid JSON.
+' -- "$BP_DIR/support/installer/" "$S3_URL" 2>&1 >$BUILD_DIR/.heroku/php/composer.json | indent || error "Couldn't parse '$COMPOSER_LOCK'; it must be valid JSON.
 Run 'composer update' to have it re-generated by Composer."
-
-if [[ ! -f "$COMPOSER_LOCK" ]]; then
-    notice_inline "No runtime required in '$COMPOSER', using PHP ^5.5.17"
-fi
 
 if composer install -d "$BUILD_DIR/.heroku/php" --no-dev 2>&1 | tee $BUILD_DIR/.heroku/php/install.log | grep --line-buffered '  - Installing heroku-sys/' | sed -u 's/  - Installing heroku-sys\//- /' | indent; then
     :
