WIP (tests) Show composer.lock lint error on failure

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -73,7 +73,7 @@ composer_lock_parse_error=$(
 		There was an error parsing '$COMPOSER_LOCK'; it must be a valid
 		file generated by Composer and be in an up-to-date state.
 
-		Look above for any parse errors and address them if necessary.
+		Look above for any errors/warnings and address them if necessary.%s
 
 		You most likely created or edited the file by hand, or a merge
 		conflict was not resolved properly, resulting in a syntax error
@@ -152,9 +152,10 @@ if [[ -s "$COMPOSER" ]]; then
 			EOF
 		}
 	else
-		cat "$COMPOSER_LOCK" | python3 -mjson.tool &> /dev/null || {
+		composer_lock_lint=$(python3 -mjson.tool "$COMPOSER_LOCK" 2>&1 >/dev/null) || {
 			mcount "failures.composer_lock.lint"
-			error "$composer_lock_parse_error"
+			printf -v composer_lock_lint_message "\n\nThe following syntax error was reported:\n%s" "$(echo "${composer_lock_lint}" | indent -i 2 -p "> ")"
+			error "$(printf "$composer_lock_parse_error" "$composer_lock_lint_message")"
 		}
 	fi
 else
@@ -467,7 +468,7 @@ export HEROKU_PHP_DEFAULT_RUNTIME_VERSION
 		error 'Invalid $HEROKU_PHP_PLATFORM_REPOSITORIES value'
 	else
 		mcount "failures.platform.composer_lock.parse"
-		error "$composer_lock_parse_error"
+		error "$(printf "$composer_lock_parse_error" "")" # printf placeholder not used here
 	fi
 }
 
