ibm_db2

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,114 +1,106 @@
-#!/bin/bash
-set -uex
-cd /tmp
+#!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir>
 
-# Heroku revision.  Must match in 'compile' program.
+# fail fast
+set -e
+
+# Heroku Revision.
 #
 # Affixed to all vendored binary output to represent changes to the
 # compilation environment without a change to the upstream version,
 # e.g. PHP 5.3.27 without, and then subsequently with, libmcrypt.
 heroku_rev='-2'
 
-# Clear /app directory
-find /app -mindepth 1 -print0 | xargs -0 rm -rf
+# config
+MCRYPT_VERSION="2.5.8"
+APACHE_VERSION="2.2.25"
+APACHE_PATH="apache"
+PHP_VERSION="5.3.27"
+PHP_PATH="php"
 
-# Take care of vendoring libmcrypt
-mcrypt_version=2.5.8
-mcrypt_dirname=libmcrypt-$mcrypt_version
-mcrypt_archive_name=$mcrypt_dirname.tar.bz2
+BIN_DIR=$(dirname $0)
+BUILD_DIR=$1
+CACHE_DIR=$2
+LP_DIR=`cd $(dirname $0); cd ..; pwd`
 
-# Download mcrypt if necessary
-if [ ! -f mcrypt_archive_name ]
-then
-    curl -Lo $mcrypt_archive_name http://sourceforge.net/projects/mcrypt/files/Libmcrypt/2.5.8/libmcrypt-2.5.8.tar.bz2/download
+# include .files when moving things around
+shopt -s dotglob
+
+cd $BUILD_DIR
+
+# move app things to www
+mkdir -p $CACHE_DIR/www
+mv * $CACHE_DIR/www
+mv $CACHE_DIR/www .
+
+# keep Procfile
+if [ -f www/Procfile ]; then
+  mv www/Procfile .
 fi
 
-# Clean and extract mcrypt
-rm -rf $mcrypt_dirname
-tar jxf $mcrypt_archive_name
+MCRYPT_URL="https://heroku-buildpack-php.s3.amazonaws.com/mcrypt-""$MCRYPT_VERSION""$heroku_rev"".tar.gz"
+echo "-----> Bundling mcrypt version $MCRYPT_VERSION"
+curl --silent --max-time 60 --location "$MCRYPT_URL" | tar xz
 
-# Build and install mcrypt.
-pushd $mcrypt_dirname
-./configure --prefix=/app/vendor/mcrypt \
-  --disable-posix-threads --enable-dynamic-loading
-make -s
-make install -s
-popd
+APACHE_URL="https://heroku-buildpack-php.s3.amazonaws.com/apache-""$APACHE_VERSION""$heroku_rev"".tar.gz"
+echo "-----> Bundling Apache version $APACHE_VERSION"
+curl --silent --max-time 60 --location "$APACHE_URL" | tar xz
 
-# Take care of vendoring Apache.
-httpd_version=2.2.25
-httpd_dirname=httpd-$httpd_version
-httpd_archive_name=$httpd_dirname.tar.bz2
+PHP_URL="https://heroku-buildpack-php.s3.amazonaws.com/php-$PHP_VERSION""$heroku_rev"".tar.gz"
+echo "-----> Bundling PHP version $PHP_VERSION"
+curl --silent --max-time 60 --location "$PHP_URL" | tar xz
 
-# Download Apache if necessary.
-if [ ! -f $httpd_archive_name ]
-then
-    curl -LO ftp://ftp.osuosl.org/pub/apache//httpd/$httpd_archive_name
-fi
+# update config files
+cp $LP_DIR/conf/httpd.conf $APACHE_PATH/conf
+cp $LP_DIR/conf/php.ini php
 
-# Clean and extract Apache.
-rm -rf $httpd_dirname
-tar jxf $httpd_archive_name
+# make php available on bin
+mkdir -p bin
+ln -s /app/php/bin/php bin/php
 
-# Build and install Apache.
-pushd $httpd_dirname
-./configure --prefix=/app/apache --enable-rewrite --with-included-apr
-make -s
-make install -s
-popd
+CLI_URL = "https://www.ng.bluemix.net/docs/Services/BluStratus/samples/clidriver.tgz"
 
-# Take care of vendoring PHP.
-php_version=5.3.27
-php_dirname=php-$php_version
-php_archive_name=$php_dirname.tar.bz2
+echo "Downloading IBM Data Server Driver...."
+curl -LO "$CLI_URL"
 
-# Download PHP if necessary.
-if [ ! -f $php_archive_name ]
-then
-    curl -Lo $php_archive_name http://us1.php.net/get/php-5.3.27.tar.bz2/from/www.php.net/mirror
-fi
+# Clean and extract DS Driver
+rm -rf clidriver
+tar -xzf clidriver.tgz
 
-# Clean and extract PHP.
-rm -rf $php_dirname
-tar jxf $php_archive_name
+IBM_DB2_URL = "http://pecl.php.net/get/ibm_db2-1.9.5.tgz"
 
+echo "Downloading IBM_DB2 source..."
+curl -LO "$IBM_DB2_URL"
 
-# Compile PHP
-pushd $php_dirname
-./configure --prefix=/app/php --with-apxs2=/app/apache/bin/apxs     \
---with-mysql --with-pdo-mysql --with-pgsql --with-pdo-pgsql         \
---with-iconv --with-gd --with-curl=/usr/lib                         \
---with-config-file-path=/app/php --enable-soap=shared               \
---with-openssl --with-mcrypt=/app/vendor/mcrypt --enable-sockets
-make -s
-make install -s
-popd
+# Clean and extract IBM_DB2
+rm -rf ibm_db2-1.9.5
+tar -xzf ibm_db2-1.9.5.tgz
 
-# Copy in MySQL client library.
-mkdir -p /app/php/lib/php
-cp /usr/lib/libmysqlclient.so.16 /app/php/lib/php
+#export PATH=/app/php/bin:$PATH
+#Build and install IBM_DB2
+#pushd "ibm_db2-1.9.5"
+#/app/php/bin/phpize
+#./configure --with-IBM_DB2=/app/clidriver
+#make -s
+#make install -s
+#popd
+#echo "extenstion=ibm_db2.so" >> /app/php/php.ini
 
-# 'apc' installation
-#
-# $PATH manipulation Necessary for 'pecl install', which relies on
-# PHP binaries relative to $PATH.
+cat >>boot.sh <<EOF
+for var in \`env|cut -f1 -d=\`; do
+  echo "PassEnv \$var" >> /app/apache/conf/httpd.conf;
+done
+touch /app/apache/logs/error_log
+touch /app/apache/logs/access_log
+tail -F /app/apache/logs/error_log &
+tail -F /app/apache/logs/access_log &
+export LD_LIBRARY_PATH=/app/php/lib/php:/app/clidriver/lib
+export PHP_INI_SCAN_DIR=/app/www
+echo "Launching apache"
+exec /app/apache/bin/httpd -DNO_DETACH
+EOF
 
-export PATH=/app/php/bin:$PATH
-/app/php/bin/pecl channel-update pecl.php.net
+chmod +x boot.sh
 
-# Use defaults for apc build prompts.
-yes '' | /app/php/bin/pecl install apc
-
-# Sanitize default cgi-bin to rid oneself of Apache sample
-# programs.
-find /app/apache/cgi-bin/ -mindepth 1 -print0 | xargs -0 rm -r
-
-# Stamp and archive binaries.
-pushd /app
-echo $mcrypt_version > vendor/mcrypt/VERSION
-tar -zcf mcrypt-"$mcrypt_version""$heroku_rev".tar.gz vendor/mcrypt
-echo $httpd_version > apache/VERSION
-tar -zcf apache-"$httpd_version""$heroku_rev".tar.gz apache
-echo $php_version > php/VERSION
-tar -zcf php-"$php_version""$heroku_rev".tar.gz php
-popd
+# clean the cache
+rm -rf $CACHE_DIR
