New formula for calculating PHP-FPM child count
The current formula, relatively crudely, divides `memory_limit` by available RAM.

On machines with a lot of available RAM (especially relative to the number of CPU cores), this can result in pretty silly PHP-FPM child counts, especially with lower `memory_limit` values.

The new formula still caps the number of child processes at `$RAM/$memory_limit`, but it yields lower values for higher RAM values (or fewer cores).

Basic calculation: `ceil(log_2($RAM / $CALC_BASE)) * $NUM_CORES * 2 * ($CALC_BASE / $memory_limit)`, where `$CALC_BASE` is `128M`.

This, very neatly, results in exactly the same numbers as the old formula for all current Heroku dyno types, but in environments with a lot of RAM, there is now a "softer" growth in the number of PHP-FPM child processes.

There is still a linear correlation between `memory_limit` and PHP-FPM child count - halving the PHP memory limit will result in doubling the number of children.

GUS-W-14634717

diff --git a/bin/heroku-php-nginx b/bin/heroku-php-nginx
--- a/bin/heroku-php-nginx
+++ b/bin/heroku-php-nginx
@@ -395,12 +395,17 @@ else
 	ram="512M"
 	echo "Assuming RAM to be ${ram} Bytes" >&2
 fi
+# read number of available processor cores in a portable (Linux, macOS, BSDs) fashion (leading underscore is not always there)
+cores=$(getconf -a | grep -E '_?NPROCESSORS_ONLN' | head -n1 | tr -s ' ' | cut -d" " -f2) || {
+	echo "WARNING: failed to determine _NPROCESSORS_ONLN via getconf" >&2
+	cores=
+}
 if [[ -z ${WEB_CONCURRENCY:-} ]]; then
-	max_ram="16G" # blanket upper limit for how much RAM we will use for PHP, unless the machine has less anyway
 	if [[ -n ${DYNO:-} && $(ulimit -u) == "32768" && ( "$php_version" == 5.* || "$php_version" == 7.[0-3].* ) ]]; then
 		# on a Performance-L dyno, limit to 6 GB of RAM for backwards compatibility for PHP versions before 7.4
 		# this is to ensure that apps previously running on PX dynos (6 GB RAM) do not get a sudden jump in the number of worker processes
-		max_ram="6G"
+		ram="6G"
+		echo "Limiting RAM usage to ${ram} Bytes" >&2
 	fi
 
 	[[ $verbose ]] && echo "Calculating WEB_CONCURRENCY..." >&2
@@ -423,8 +428,8 @@ if [[ -z ${WEB_CONCURRENCY:-} ]]; then
 	# determine number of FPM processes to run
 	# we feed it the PHP config we found much earlier (it must be the one FPM loads, not the CLI one!), docroot (for .user.ini), detected RAM, and RAM cap
 	# on STDIN, we also pass it any php_value or php_admin_value lines from the FPM config dump that may have a memory_limit (via a herestring, easier than echo)
-	WEB_CONCURRENCY=$(php ${php_config:+-c "$php_config"} -f "$bp_dir/bin/util/autotune.php" -- ${verbose:+-v} -t "$DOCUMENT_ROOT" "$ram" "$max_ram" <<<"$fpm_limits")
-	[[ $verbose ]] && echo "WEB_CONCURRENCY=${WEB_CONCURRENCY} (RAM / memory_limit)" >&2
+	WEB_CONCURRENCY=$(php ${php_config:+-c "$php_config"} -f "$bp_dir/bin/util/autotune.php" -- ${verbose:+-v} -t "$DOCUMENT_ROOT" "$ram" $cores <<<"$fpm_limits")
+	[[ $verbose ]] && echo "WEB_CONCURRENCY=${WEB_CONCURRENCY}" >&2
 	[[ $WEB_CONCURRENCY -lt 1 ]] && { WEB_CONCURRENCY=1; [[ $verbose ]] && echo "WEB_CONCURRENCY=1 (was below mininum)" >&2; }
 	export WEB_CONCURRENCY
 else
