new boot for nginx with options, configs, config includes, a ton of checks and all the bells and whistles

diff --git a/bin/heroku-php-nginx b/bin/heroku-php-nginx
--- a/bin/heroku-php-nginx
+++ b/bin/heroku-php-nginx
@@ -4,12 +4,15 @@
 set -o pipefail
 # fail harder
 set -eu
+# for patterns further down
+shopt -s extglob
 
 php_passthrough() {
     local dir=`dirname $1`
     local file=`basename $1`
     local out=`basename $file .php`
     if [[ "$out" != "$file" ]]; then
+        echo "Interpreting ${1#$HEROKU_APP_DIR/} to $out" >&2
         out="$dir/$out"
         php $1 > $out
         echo $out
@@ -18,67 +21,144 @@ php_passthrough() {
     fi
 }
 
+check_exists() {
+    if [[ ! -f "$HEROKU_APP_DIR/$1" ]]; then
+        echo "Cannot read -$2 '$1' (relative to '$HEROKU_APP_DIR')" >&2
+        exit 1
+    else
+        echo "$HEROKU_APP_DIR/$1"
+    fi
+}
+
+print_help() {
+echo "\
+Boots PHP-FPM together with Nginx on Heroku and for local development.
+
+Usage:
+  heroku-php-nginx [options] [<DOCUMENT_ROOT>]
+
+Options:
+  -C <nginx.inc.conf>     The path to the configuration file to include inside
+                          the Nginx server config (see option -c below). Will
+                          be included inside the 'server { ... }' block just
+                          after the 'listen', 'root' etc directives.
+                          Recommended approach when customizing Nginx's config
+                          in most cases, unless you need to set http or
+                          fundamental server level options.
+                          [default: $COMPOSER_VENDOR_DIR/heroku/heroku-buildpack-php/conf/nginx/heroku_site.conf.php]
+  -c <nginx.conf>         The path to the full configuration file that is
+                          included after Heroku's (or your local) Nginx config
+                          is loaded. It must contain an 'http { ... }' block
+                          with a 'server { ... }' inside (see option -C above),
+                          but no global directives (those are taken from the
+                          default Nginx configuration).
+                          [default: $COMPOSER_VENDOR_DIR/heroku/heroku-buildpack-php/conf/nginx/heroku.conf.php]
+  -F <php-fpm.inc.conf>   The path to the configuration file to include at the  
+                          end of php-fpm.conf (see option -f below), in the
+                          '[www]' pool section. Recommended approach when
+                          customizing PHP-FPM's configuration in most cases,
+                          unless you need to set global options.
+  -f <php-fpm.conf>       The path to the full PHP-FPM configuration file.
+                          [default: $COMPOSER_VENDOR_DIR/heroku/heroku-buildpack-php/conf/php/php-fpm.conf]
+  -h                      Display this help screen and exit.
+  -i <php.ini>            The path to the php.ini file to use.
+                          [default: $COMPOSER_VENDOR_DIR/heroku/heroku-buildpack-php/conf/php/php.ini]
+
+Any file name that ends in '.php' will be run through the PHP interpreter first.
+You may use this for templating; this is, for instance, necessary for Nginx,
+where environment variables cannot be referenced in configuration files.
+All file paths must be relative to '$HEROKU_APP_DIR'.
+
+If you would like to use the -C and -c or -F and -f options together, make sure
+you retain the appropriate include mechanisms (see default configs for details).
+" >&2
+}
+
 # we need this in configs
 export HEROKU_APP_DIR=`pwd`
 export DOCUMENT_ROOT="$HEROKU_APP_DIR"
 # set a default port if none is given
 export PORT=${PORT:-$(( $RANDOM+1024 ))}
+COMPOSER_VENDOR_DIR=`composer config vendor-dir`
 
-nginx_user_config=""
-php="php-fpm --nodaemonize -y $HEROKU_APP_DIR/vendor/heroku/heroku-buildpack-php/conf/php/php-fpm.conf -c $HEROKU_APP_DIR/vendor/heroku/heroku-buildpack-php/conf/php/php.ini"
-test=0
-while getopts ":n:f:t" opt; do
+while getopts ":C:c:F:f:i:h" opt; do
     case $opt in
-        n)
-            if [[ -z $OPTARG ]]; then
-                echo "Must give additional nginx.conf path (relative to '$HEROKU_APP_DIR')" >&2
-                exit 1
-            fi
-            # FIXME: check if it exists
-            nginx_user_config=$(php_passthrough "$HEROKU_APP_DIR/$OPTARG")
-            echo "Using additional Nginx configuration file '$nginx_user_config'" >&2
-            nginx_user_config="include $nginx_user_config;"
+        C)
+            nginx_config_include=$(check_exists "$OPTARG" "C")
+            ;;
+        c)
+            nginx_config=$(check_exists "$OPTARG" "c")
+            ;;
+        F)
+            fpm_config_include=$(check_exists "$OPTARG" "F")
             ;;
         f)
-            if [[ -z $OPTARG ]]; then
-                echo "Must give custom php-fpm.conf path (relative to '$HEROKU_APP_DIR')" >&2
-                exit 1
-            fi
-            # FIXME: check if it exists
-            php="$php -y $HEROKU_APP_DIR/$OPTARG" # can safely repeat to overwrite
-            echo "Using custom PHP-FPM configuration file '$HEROKU_APP_DIR/$OPTARG'" >&2
+            fpm_config=$(check_exists "$OPTARG" "f")
             ;;
         i)
-            if [[ -z $OPTARG ]]; then
-                echo "Must give custom php.ini path (relative to '$HEROKU_APP_DIR')" >&2
-                exit 1
-            fi
-            # FIXME: check if it exists
-            php="$php -c $HEROKU_APP_DIR/$OPTARG" # can safely repeat to overwrite
-            echo "Using custom PHP INI file '$HEROKU_APP_DIR/$OPTARG'" >&2
+            php_config=$(check_exists "$OPTARG" "i")
+            ;;
+        h)
+            print_help 2>&1
+            exit
             ;;
         \?)
             echo "Invalid option: -$OPTARG" >&2
-            exit 1
+            exit 2
             ;;
         :)
-            echo "Option -$OPTARG requires an argument." >&2
-            exit 1
+            echo "Option -$OPTARG requires an argument" >&2
+            exit 2
             ;;
     esac
 done
 # clear processed arguments
 shift $((OPTIND-1))
 
+if [[ "$#" -gt "1" ]]; then
+    print_help
+    exit 2
+fi
+
 php -r 'exit((int)version_compare(PHP_VERSION, "5.5.11", "<"));' || { echo "This program requires PHP 5.5.11 or newer" >&2; exit 1; }
 
 echo "Booting on port $PORT..." >&2
 
-if [ "$#" == "1" ]; then
-    # FIXME: check if it exists, strip trailing slashes
+if [[ "$#" == "1" ]]; then
     DOCUMENT_ROOT="$HEROKU_APP_DIR/$1"
-    echo "DOCUMENT_ROOT changed to '$DOCUMENT_ROOT'" >&2
+    if [[ ! -d "$DOCUMENT_ROOT" ]]; then
+        echo "DOCUMENT_ROOT '$1' does not exist"
+        exit 1
+    else
+        # strip trailing slashes if present
+        DOCUMENT_ROOT=${DOCUMENT_ROOT%%*(/)}
+        echo "DOCUMENT_ROOT changed to '$DOCUMENT_ROOT'" >&2
+    fi
 fi
+
+fpm_config_include=${fpm_config_include:-}
+if [[ -n "$fpm_config_include" ]]; then
+    echo "Using PHP-FPM configuration include '${fpm_config_include#$HEROKU_APP_DIR/}'" >&2
+    fpm_config_include=$(php_passthrough "$fpm_config_include")
+    export HEROKU_PHP_FPM_CONFIG_INCLUDE="$fpm_config_include"
+fi
+
+fpm_config=${fpm_config:-"$HEROKU_APP_DIR/$COMPOSER_VENDOR_DIR/heroku/heroku-buildpack-php/conf/php/php-fpm.conf"}
+echo "Using PHP-FPM configuration file '${fpm_config#$HEROKU_APP_DIR/}'" >&2
+fpm_config=$(php_passthrough "$fpm_config")
+
+php_config=${php_config:-"$HEROKU_APP_DIR/$COMPOSER_VENDOR_DIR/heroku/heroku-buildpack-php/conf/php/php.ini"}
+echo "Using PHP configuration (php.ini) file '${php_config#$HEROKU_APP_DIR/}'" >&2
+php_config=$(php_passthrough "$php_config")
+
+nginx_config_include=${nginx_config_include:-"$HEROKU_APP_DIR/$COMPOSER_VENDOR_DIR/heroku/heroku-buildpack-php/conf/nginx/default_include.conf"}
+echo "Using Nginx server-level configuration include '${nginx_config_include#$HEROKU_APP_DIR/}'" >&2
+nginx_config_include=$(php_passthrough "$nginx_config_include")
+export HEROKU_PHP_NGINX_CONFIG_INCLUDE="$nginx_config_include"
+
+nginx_config=${nginx_config:-"$HEROKU_APP_DIR/$COMPOSER_VENDOR_DIR/heroku/heroku-buildpack-php/conf/nginx/heroku.conf.php"}
+echo "Using Nginx configuration file '${nginx_config#$HEROKU_APP_DIR/}'" >&2
+nginx_config=$(php_passthrough "$nginx_config")
 
 # make a shared pipe; we'll write the name of the process that exits to it once that happens, and wait for that event below
 # this particular call works on Linux and Mac OS (will create a literal ".XXXXXX" on Mac, but that doesn't matter).
@@ -99,11 +179,10 @@ echo "Starting log redirection..." >&2
 ( touch "/tmp/heroku.php-fpm.$PORT.log" "/tmp/heroku.nginx_access.$PORT.log"; tail -qF -n 0 /tmp/heroku.*.$PORT.log 1>&2; echo "tail heroku.*.$PORT.log"; ) > $wait_pipe &
 # start FPM; write "php-fpm" to the shared pipe if it exits
 echo "Starting php-fpm..." >&2
-( $php; echo "php-fpm"; ) > $wait_pipe &
+( php-fpm --nodaemonize -y "$fpm_config" -c "$php_config"; echo "php-fpm"; ) > $wait_pipe &
 # start nginx; write "nginx" to the shared pipe if it exits
 echo "Starting nginx..." >&2
-nginx_config=$(php_passthrough "$HEROKU_APP_DIR/vendor/heroku/heroku-buildpack-php/conf/nginx/heroku.conf.php")
-( nginx -g "daemon off; include $nginx_config; $nginx_user_config"; echo "nginx"; ) > $wait_pipe &
+( nginx -g "daemon off; include $nginx_config;"; echo "nginx"; ) > $wait_pipe &
 
 # wait for something to come from the shared pipe, which means that the given process was killed or has failed
 # we'll only reach this if one of the processes above has terminated
