Improve memory_limit detection
Turns out that bug which would not allow overriding of FPM config php_value settings in .user.ini was fixed in... PHP 7.2: https://bugs.php.net/bug.php?id=75212

Also, that behavior where a later declaration does not override a newer one is probably a bug: https://github.com/php/php-src/issues/13249

We now use php-fpm -tt to dump the config, since that will have stuff printed in evaluation order - if the bug above ever gets fixed, we have to do nothing.

This also removes the need for us to handle the PHP-FPM config include directives ourselves, and as a result, variable expansion and globbing now work in these!

GUS-W-14901875

diff --git a/bin/heroku-php-apache2 b/bin/heroku-php-apache2
--- a/bin/heroku-php-apache2
+++ b/bin/heroku-php-apache2
@@ -402,8 +402,26 @@ if [[ -z ${WEB_CONCURRENCY:-} ]]; then
 		max_ram="6G"
 	fi
 
+	# dump the FPM config and parse out memory_limit declarations
+	# for that to work, we need the WEB_CONCURRENCY env var set, as the FPM config references it
+	export WEB_CONCURRENCY=1
+	# inside this subshell, we want pipefail on to ensure that a failing FPM command causes an exit
+	# grep might not match anything, so if it doesn't (status 1), we carry on, since that's fine (but other exit statuses will bubble up)
+	fpm_limits=$(set -o pipefail; "${fpm_command[@]}" -tt 2>&1 | { grep -E $'NOTICE: \tphp(_admin)?_value\[memory_limit\]' || test $? = 1; } | cut -f2) || {
+		# on failure, we should output something meaningful
+		echo "PHP-FPM config test failed with status $?:" >&2
+		# restore the original config to avoid any potential for confusion
+		cp "$fpm_config" "$fpm_config_tmp"
+		# single -t is enough this time
+		"${fpm_command[@]}" -t
+		exit 1
+	}
+
 	# determine number of FPM processes to run
-	read WEB_CONCURRENCY php_memory_limit <<<$(php ${php_config:+-c "$php_config"} "$bp_dir/bin/util/autotune.php" -y "$fpm_config" -t "$DOCUMENT_ROOT" "$ram" "$max_ram")
+	# we feed it the PHP config we found much earlier (it must be the one FPM loads, not the CLI one!), docroot (for .user.ini), detected RAM, and RAM cap
+	# on STDIN, we also pass it any php_value or php_admin_value lines from the FPM config dump that may have a memory_limit (via a herestring, easier than echo)
+	# the output is then passed into read via a herestring; read creates our variables (we cannot pipe into read, since pipelines are a subshell, and then variables would be gone straight after)
+	read WEB_CONCURRENCY php_memory_limit <<<$(php ${php_config:+-c "$php_config"} "$bp_dir/bin/util/autotune.php" -t "$DOCUMENT_ROOT" "$ram" "$max_ram" <<<"$fpm_limits")
 	[[ $WEB_CONCURRENCY -lt 1 ]] && WEB_CONCURRENCY=1
 	export WEB_CONCURRENCY
 
