fix rare startup failure race condition
if FPM fails to launch, e.g. because of a config error, there is a small chance the resulting cleanup procedure will hit the web server subshell at just the wrong moment, causing it to hang in wait_pidfile forever (which then eventually gets terminated by the dyno manager)

this change adds a timeout of 2500 ms, after which the function returns 1, and calling code can use that to exit

diff --git a/bin/heroku-php-apache2 b/bin/heroku-php-apache2
--- a/bin/heroku-php-apache2
+++ b/bin/heroku-php-apache2
@@ -70,20 +70,32 @@ findconfig() {
 }
 
 wait_pidfile() {
-	while ! test -f "$1"; do
+	i=0
+	while ! test -f "$1" && (( i < 25 )); do
 		[[ $verbose && ${2:-} ]] && echo "$2" >&2
 		sleep 0.1
+		((++i)) # don't do i++, that is a post increment operation, and will return status 1, since the expression evaluates to 0...
 	done
+	if (( i == 25 )); then
+		# we timed out
+		return 1;
+	fi
 }
 
 wait_pid_and_pidfile() {
-	while ! test -f "$2"; do
+	i=0
+	while ! test -f "$2" && (( i < 25 )); do
 		if ! kill -0 "$1" 2> /dev/null; then # kill -0 checks if process exists
 			break;
 		fi
 		[[ $verbose && ${3:-} ]] && echo "$3" >&2
 		sleep 0.1
+		((++i)) # don't do i++, that is a post increment operation, and will return status 1, since the expression evaluates to 0...
 	done
+	if (( i == 25 )); then
+		# we timed out
+		return 1;
+	fi
 }
 
 print_help() {
@@ -496,8 +508,9 @@ httpd_pidfile=$(httpd -t -D DUMP_RUN_CFG 2> /dev/null | sed -n -E 's/PidFile: "(
 
 	# wait for FPM to write its PID file, which it does after initialization
 	# if we didn't wait, the web server would start sending traffic to the FCGI backend before it's ready (or before the socket is even created)
-	# if FPM fails to start, the while loop below will not loop forever, because the FPM subshell will exit, causing the main cleanup procedure to run, which sends this subshell a SIGTERM, which terminates the while loop below after the next sleep execution
-	wait_pidfile "$fpm_pidfile" "Waiting for php-fpm to finish initializing..."
+	# if FPM fails to start, the FPM subshell will exit, causing the main cleanup procedure to run, which sends this subshell a SIGTERM
+	# there is however a possible race condition where this happens exactly the moment we hit the function below, which is why it internally has a timeout of 2500 ms, and we use that to exit 1
+	wait_pidfile "$fpm_pidfile" "Waiting for php-fpm to finish initializing..." || { echo "Timed out waiting for php-fpm." >&2; exit 1; }
 
 	echo "Starting httpd..." >&2
 
