make sure all subprocess exits are caught properly

diff --git a/bin/heroku-hhvm-apache2 b/bin/heroku-hhvm-apache2
--- a/bin/heroku-hhvm-apache2
+++ b/bin/heroku-hhvm-apache2
@@ -148,16 +148,18 @@ mkfifo $wait_pipe
 # 1) restore EXIT trap immediately, or the exit at the end of the line will trigger this trap again
 # 2) kill childrens' child processes (the stuff running inside the sub-shells) using xargs because this is easier (-P expects a comma separated list); the || true prevents premature exit (set -e) if one of those doesn't have children anymore (it's likely that's why we're hitting this bit of code in the first place)
 # 3) kill child processes (that's the sub-shells); it's likely that some of them have already disappeared, so xarg || true it too and suppress "no such process" complaints by sending them to /dev/null
-# FIXME: this doesn't currently fire when the subshells themselves are terminated, and apparently also not when killing the tail command
+# FIXME: this doesn't currently fire when the subshells themselves are terminated
 # TODO: for extra brownie points, move to a function and curry for each given signal, passing the signal in as an arg, so we can use different exit codes or messages
 trap 'trap - EXIT; echo "Going down, terminating child processes..." >&2; jobs -p | xargs -n1 pkill -TERM -P || true; jobs -p | xargs -n1 kill -TERM 2> /dev/null || true; exit' SIGINT SIGQUIT SIGTERM EXIT
 
+# launch processes. all run using || true to prevent premature exit of the subshell (from set -e) regardless of exit status
+
 # redirect logs to STDERR; write "tail ..." to the shared pipe if it exits
 echo "Starting log redirection..." >&2
-( touch "/tmp/heroku.apache2_error.$PORT.log" "/tmp/heroku.apache2_access.$PORT.log"; tail -qF -n 0 /tmp/heroku.*.$PORT.log 1>&2; echo "tail heroku.*.$PORT.log" >&3; ) 3> $wait_pipe &
+( touch "/tmp/heroku.apache2_error.$PORT.log" "/tmp/heroku.apache2_access.$PORT.log"; tail -qF -n 0 /tmp/heroku.*.$PORT.log 1>&2 || true; echo "tail heroku.*.$PORT.log" >&3; ) 3> $wait_pipe &
 # start HHVM; write "hhvm" to the shared pipe if it exits
 echo "Starting hhvm..." >&2
-( hhvm --mode server -vServer.Type=fastcgi -vServer.FileSocket=/tmp/heroku.fcgi.$PORT.sock -c "$php_config"; echo "hhvm" >&3; ) 3> $wait_pipe &
+( hhvm --mode server -vServer.Type=fastcgi -vServer.FileSocket=/tmp/heroku.fcgi.$PORT.sock -c "$php_config" || true; echo "hhvm" >&3; ) 3> $wait_pipe &
 # wait a few seconds for HHVM to finish initializing; otherwise an early request might break Apache with the FastCGI pipe not being ready
 # start apache; write "httpd" to the shared pipe if it exits
 echo "Starting httpd..." >&2
