Improve handling of concurrent or unknown signals
When we are, for whatever reason, sent the same signal multiple times, the very first operation inside the trap ('trap - ...') currently re-sets the signal handler (to SIG_DFL). Since Bash 4.3 RC2, delivery of signals is no longer blocked during the execution of traps for those same signals (i.e., the same trap handler that is executing fires again during its own execution). Since we've re-set to SIG_DFL at the beginning of the trap, if another TERM signal arrives while the trap is running, the default behavior of immediate termination kicks in, which also kills the currently running trap and its cleanup procedure.

Instead, we now perform a 'trap "" ...' to instead ignore this signal immediately (SIG_IGN), perform the cleanup, and then re-set the trap to the default handler before triggering it by sending the signal to ourselves - this is the correct behavior for a program that terminates in response to a signal in order for other programs to be able to correctly determine the cause of a termination (so e.g. when receiving SIGTERM, a program must, as its final action, kill itself using that signal, and not exit with e.g. 0).

This means that the subshells will now exit with a non-0 exit status; this triggers an error condition in the main shell, which fires off the signal handler for the signal received - so a subshell that terminates with 'kill -USR1 $$' in response to a USR1 signal will have an exit status of 128+USR1, and trigger a USR1 signal in the main shell. That's why we ignore that USR1 signal before issuing the cleanup, since it would otherwise trigger the (now reset) EXIT handler, and terminate the outer shell.

This behavior is quite useful for any unhandled signals now - if the main program or a subshell receive e.g. a USR2, which by default causes termination, the main EXIT trap fires and tears stuff down.

There is a possible race condition in Bash's delivery of signals to trap handlers that will occasionally cause the internal trap list to become corrupted if signals arrive in rapid succession between the execution of a trap and the changing of a signal handler (to SIG_IGN in our case). This is often, but not always, accompanied by a message like "warning: run_pending_traps: bad value in trap_list[15]", and it will happen if signals arrive in rapid succession (see run_pending_traps() in Bash's trap.c).

If this occurs, the re-setting of the trap to SIG_DFL, and the subsequent termination due to the 'kill -$SIGNAL $$', will not execute (and the bash process will hang indefinitely) until the trap exits for another reason. We "trigger" this exiting with an explicit 'exit 0' call in the outer shell's traps (in this case, the exit 0 will not actually execute, and the termination status of the outer process will be the correct e.g. "143" status code representing termination in response to SIGTERM). In the subshells, this is not necessary, because they get cleaned up by the outer bash process later.

GUS-W-15071619

diff --git a/bin/heroku-php-nginx b/bin/heroku-php-nginx
--- a/bin/heroku-php-nginx
+++ b/bin/heroku-php-nginx
@@ -492,18 +492,23 @@ if [[ -n "${DYNO:-}" && "${HEROKU_PHP_GRACEFUL_SIGTERM:-1}" != "0" ]]; then
 fi
 
 # trap SIGTERM (for when we get killed) and EXIT (upon failure of any command due to set -e, or because of the exit at the very end), we then
-# 1) restore the trap for the signal in question so it doesn't fire again due to the kill at the end of the trap, as well as for EXIT, because that would fire too
+# 1) ignore the trap for the signal in question so it doesn't fire again should the signal arrive a second time (this happens, e.g. when 'timeout' terminates something)
+# 1a) such a second identical signal arriving may occasionally cause a "warning: run_pending_traps: bad value in trap_list[15]: 0x1" due to a race condition in Bash versions before 5.1, see 4b)
 # 2) call cleanup() to
 # 2a) kill all the subshells we've spawned, in reverse order - they in turn have their own traps to kill their respective subprocesses
 # 2b) send STDERR to /dev/null so we don't see "no such process" errors - after all, one of the subshells may be gone
 # 2c) || true so that set -e doesn't cause a mess if the kill returns 1 on "no such process" cases
 # 2d) 'wait' on that killed subprocess, sending wait's output to /dev/null - this prevents the logs getting cluttered with "vendor/bin/heroku-...: line 309:    96 Terminated" messages (we can't use 'disown' after launching programs for that purpose because that removes the jobs from the shell's jobs table and then we can no longer 'wait' on the program)
 # 2e) remove our FIFO from above
-# 3) as the signal to subshells, we use SIGUSR1 if we're getting a SIGTERM or SIGINT (for graceful shutdown), and a SIGTERM otherwise
+# 3) as the signal to subshells, we use SIGUSR1
 # 3a) this is so subshells can tell whether we sent them the signal and they should in turn stop gracefully (SIGUSR1)...
 # 3b) ... or if something crashed, or e.g. Heroku's process manager sent SIGTERM to all processes in the group, in which case a graceful shutdown attempt is futile anyway
 # 3c) SIGINT oder SIGQUIT are not an option since backgrounded subshells cannot trap them (http://vaab.blog.kal.fr/2016/07/30/trapping-sigint-sigquit-in-asynchronous-tasks/) in Bash 3 (it works in Bash 4+ in interactive shells at least)
+# 3d) because we're sending SIGUSR1 via cleanup(), we have to ignore that signal right before - otherwise, the backgrounded subshells exiting upon this exit status would cause our main process to terminate due to set -e
+# 3e) we do not simply set USR1 to ignored globally, because then we would not catch the case where something external sends a USR1 to our subshell - instead, our exit trap will fire in these cases where we did not initiate the cleanup, and tear everything down
 # 4) kill ourselves with the correct signal in case we're handling SIGTERM or, further down, SIGINT (http://www.cons.org/cracauer/sigint.html and http://mywiki.wooledge.org/SignalTrap#Special_Note_On_SIGINT1)
+# 4a) we have to re-set the trap handler to the default (using "-") for that
+# 4b) we still exit 0 as a last resort, because Bash has a race condition bug (see run_pending_traps in trap.c) where if another signal arriving during the 'trap "" TERM' call (to ignore the same signal and prevent multiple executions), the trap would hang at the end, despite the 'kill -TERM $$'
 cleanup() {
 	signal=${1:-TERM}
 	# reverse through list of child processes and kill them
@@ -515,15 +520,18 @@ cleanup() {
 	rm -f ${wait_pipe} || true;
 	echo "Shutdown complete." >&2
 }
+
 # we always try to shut down gracefully on SIGTERM
 # this may not work depending on env vars and platform behavior, but the subshells will take care of those details
-trap 'trap - TERM EXIT; echo "SIGTERM received, attempting graceful shutdown..." >&2; cleanup USR1; kill -TERM $$' TERM
+trap 'trap "" TERM; trap - EXIT; echo "SIGTERM received, attempting graceful shutdown..." >&2; trap "" USR1; cleanup USR1; trap - TERM; kill -TERM $$; exit 0' TERM
+
 # on "regular" EXIT (i.e. when we reached the end of the script because a process exited unexpectedly) just clean up and let the exit status bubble through (see last line)
-trap 'trap - EXIT; echo "Process exited unexpectedly: $exitproc, shutting down..." >&2; cleanup USR1' EXIT
+# this will also fire when any unhandled signal is received, in which case $exitproc will be unset
+trap 'echo "Process exited unexpectedly: ${exitproc-$(basename $0)}, shutting down..." >&2; trap "" USR1; cleanup USR1' EXIT
 
 # if FD 1 is a TTY (that's the -t 1 check), trap SIGINT/Ctrl+C, then same procedure as for TERM above
 if [[ -t 1 ]]; then
-	trap 'trap - INT EXIT; echo "SIGINT received, initiating graceful shutdown..." >&2; cleanup USR1; kill -INT $$' INT;
+	trap 'trap "" INT; trap - EXIT; echo "SIGINT received, initiating graceful shutdown..." >&2; trap "" USR1; cleanup USR1; trap - INT; kill -INT $$; exit 0' INT;
 # if FD 1 is not a TTY (e.g. when we're run through 'foreman start'), do nothing on SIGINT; the assumption is that the parent will send us a SIGTERM or something when this happens. With the trap above, Ctrl+C-ing out of a 'foreman start' run would trigger the INT trap both in Foreman and here (because Ctrl+C sends SIGINT to the entire process group, but there is no way to tell the two cases apart), and while the trap is still doing its shutdown work triggered by the SIGTERM from the Ctrl+C, Foreman would then send a SIGTERM because that's what it does when it receives a SIGINT itself.
 else
 	trap '' INT;
@@ -537,6 +545,7 @@ fi
 # 2b) a second 'wait' then ensures that the subshell remains alive until the process inside has shut down
 # 2c) both 'wait' calls use || true to prevent 'set -e' failures: 'wait' returns the exit status of the given program, and that won't be zero, because it's getting killed
 # 2d) we restore traps before the second wait, because restoring them inside the trap handler occasionally caused bizarre signal handling failures
+# 2e) inside the TERM and USR1 traps, we ignore both of those signals as the very first thing, to ensure another similar signal arriving does not interrupt our shutdown
 # 3) each subshell has another trap on INT which does nothing (to prevent Ctrl+C interference)
 # 4) we execute the command in the background, recording its PID(s) for the subshell's TERM trap
 # 5) we also execute the subshell in the background, recording its PID for the main TERM/INT traps
@@ -584,12 +593,12 @@ fi
 	) & logs_procs+=($!)
 	# after the kill, we are redirecting stderr to /dev/null using exec to suppress "… Terminated …" messages from the shell, which it would print right before the next command is invoked
 	# we have to send SIGHUP to each process (could also use SIGUSR1 or any other process where the default behavior is termination, see https://man7.org/linux/man-pages/man7/signal.7.html); SIGQUIT or SIGINT doesn't work - this is because of the SIG_IGN workaround above, which is done using a backgrounded subshell and an exec - and backgrounded subshells cannot trap SIGTERM or SIGINT: http://vaab.blog.kal.fr/2016/07/30/trapping-sigint-sigquit-in-asynchronous-tasks/
-	trap '[[ $verbose ]] && echo "Stopping log redirection..." >&2; kill -HUP "${logs_procs[@]}" 2> /dev/null || true; exec 2> /dev/null' USR1
+	trap 'trap "" USR1; trap - EXIT; [[ $verbose ]] && echo "Stopping log redirection..." >&2; kill -HUP "${logs_procs[@]}" 2> /dev/null || true; exec 2> /dev/null; wait "${logs_procs[@]}" 2> /dev/null || true; trap - USR1; kill -USR1 $$' USR1
 	# ignore process group wide SIGTERM for this subshell if that env var is set
 	if [[ $graceful_sigterm ]]; then
 		trap '' TERM
 	else
-		trap '[[ $verbose ]] && echo "Stopping log redirection..." >&2; kill -TERM "${logs_procs[@]}" 2> /dev/null || true; exec 2> /dev/null' TERM
+		trap 'trap "" TERM; trap - EXIT; [[ $verbose ]] && echo "Stopping log redirection..." >&2; kill -TERM "${logs_procs[@]}" 2> /dev/null || true; exec 2> /dev/null; wait "${logs_procs[@]}" 2> /dev/null || true; trap - TERM; kill -TERM $$' TERM
 	fi
 
 	wait 2> /dev/null || true # redirect stderr to prevent possible trap race condition warnings
@@ -616,12 +625,12 @@ fi
 	# execute the command we built earlier, with the correct quoting etc expanded
 	"${fpm_command[@]}" & pid=$!
 	# wait for the pidfile in the trap; otherwise, a previous subshell failing may result in us getting a SIGTERM and forwarding it to the child process before that child process is ready to process signals
-	trap 'echo "Stopping php-fpm gracefully..." >&2; wait_pid_and_pidfile $pid "$fpm_pidfile"; kill -QUIT $pid 2> /dev/null || true' USR1
+	trap 'trap "" USR1; trap - EXIT; echo "Stopping php-fpm gracefully..." >&2; wait_pid_and_pidfile $pid "$fpm_pidfile"; kill -QUIT $pid 2> /dev/null || true; wait $pid 2> /dev/null || true; trap - USR1; kill -USR1 $$' USR1
 	# we always want to try and stop gracefully, especially since on Heroku we might be getting a process group wide SIGTERM but running a patched PHP-FPM that ignores SIGTERM; so if that env var is set, we ignore SIGTERM in this subshell as well
 	if [[ $graceful_sigterm ]]; then
 		trap '' TERM
 	else
-		trap 'echo "Stopping php-fpm..." >&2; wait_pid_and_pidfile $pid "$fpm_pidfile"; kill -TERM $pid 2> /dev/null || true' TERM
+		trap 'trap "" TERM; trap - EXIT; echo "Stopping php-fpm..." >&2; wait_pid_and_pidfile $pid "$fpm_pidfile"; kill -TERM $pid 2> /dev/null || true; wait $pid 2> /dev/null || true; trap - TERM; kill -TERM $$' TERM
 	fi
 
 	wait $pid 2> /dev/null || true # redirect stderr to prevent possible trap race condition warnings
@@ -645,12 +654,12 @@ fi
 	# execute the command we built earlier, with the correct quoting etc expanded
 	"${nginx_command[@]}" & pid=$!
 	# wait for the pidfile in the trap; otherwise, a previous subshell failing may result in us getting a SIGTERM and forwarding it to the child process before that child process is ready to process signals
-	trap 'echo "Stopping nginx gracefully..." >&2; wait_pid_and_pidfile $pid "$nginx_pidfile"; kill -QUIT $pid 2> /dev/null || true' USR1
+	trap 'trap "" USR1; trap - EXIT; echo "Stopping nginx gracefully..." >&2; wait_pid_and_pidfile $pid "$nginx_pidfile"; kill -QUIT $pid 2> /dev/null || true; wait $pid 2> /dev/null || true; trap - USR1; kill -USR1 $$' USR1
 	# we always want to try and stop gracefully, especially since on Heroku we might be getting a process group wide SIGTERM but running a patched Nginx that ignores SIGTERM; so if that env var is set, we ignore SIGTERM in this subshell as well
 	if [[ $graceful_sigterm ]]; then
 		trap '' TERM
 	else
-		trap 'echo "Stopping nginx..." >&2; wait_pid_and_pidfile $pid "$nginx_pidfile"; kill -TERM $pid 2> /dev/null || true' TERM
+		trap 'trap "" TERM; trap - EXIT; echo "Stopping nginx..." >&2; wait_pid_and_pidfile $pid "$nginx_pidfile"; kill -TERM $pid 2> /dev/null || true; wait $pid 2> /dev/null || true; trap - TERM; kill -TERM $$' TERM
 	fi
 
 	# first, we wait for the pid file to be written, so that we can emit a ready message
