quiet apt-get in builds

diff --git a/support/build/extensions/no-debug-non-zts-20121212/memcached-bare b/support/build/extensions/no-debug-non-zts-20121212/memcached-bare
--- a/support/build/extensions/no-debug-non-zts-20121212/memcached-bare
+++ b/support/build/extensions/no-debug-non-zts-20121212/memcached-bare
@@ -47,8 +47,8 @@ else
     needed=( libmemcached-dev )
     missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
     if [[ "$missing" ]]; then
-        apt-get update || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
-        apt-get install -y $missing
+        apt-get update -qq || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
+        apt-get install -q -y $missing
     fi
 fi
 
@@ -56,8 +56,8 @@ fi
 needed=( libsasl2-dev )
 missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
 if [[ "$missing" ]]; then
-    apt-get update || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
-    apt-get install -y $missing
+    apt-get update -qq || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
+    apt-get install -q -y $missing
 fi
 
 curl -L ${dep_url} | tar xz
diff --git a/support/build/libraries/libc-client b/support/build/libraries/libc-client
--- a/support/build/libraries/libc-client
+++ b/support/build/libraries/libc-client
@@ -24,9 +24,9 @@ echo "-----> Building ${dep_package}..."
 # we need that for IMAP
 needed=( libpam0g-dev )
 missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
-if [[ -n "$missing" ]]; then
-    apt-get update || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
-    apt-get install -y $missing
+if [[ "$missing" ]]; then
+    apt-get update -qq || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
+    apt-get install -q -y $missing
 fi
 
 curl -L ${dep_url} | tar xz
diff --git a/support/build/libraries/libmemcached b/support/build/libraries/libmemcached
--- a/support/build/libraries/libmemcached
+++ b/support/build/libraries/libmemcached
@@ -35,8 +35,8 @@ if [[ "$missing" ]]; then
     needed=( libsasl2-dev )
     missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
     if [[ "$missing" ]]; then
-        apt-get update || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
-        apt-get install -y $missing
+        apt-get update -qq || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
+        apt-get install -q -y $missing
     fi
     echo "-----> Building ${dep_package}..."
 
diff --git a/support/build/php b/support/build/php
--- a/support/build/php
+++ b/support/build/php
@@ -52,8 +52,8 @@ fi
 needed=( libgmp-dev libpam0g-dev libicu-dev libsasl2-dev libkrb5-dev libldap2-dev )
 missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
 if [[ "$missing" ]]; then
-    apt-get update || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
-    apt-get install -y $missing
+    apt-get update -qq || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
+    apt-get install -q -y $missing
 fi
 
 # look for GMP libs in /usr/lib/x86_64-linux-gnu and not /usr/lib
@@ -80,8 +80,8 @@ else
     needed=( libmcrypt-dev )
     missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
     if [[ "$missing" ]]; then
-        apt-get update || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
-        apt-get install -y $missing
+        apt-get update -qq || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
+        apt-get install -q -y $missing
     fi
 fi
 
