use system libmcrypt and libmemcached if possible
both are available on heroku-16

diff --git a/support/build/extensions/no-debug-non-zts-20121212/memcached-bare b/support/build/extensions/no-debug-non-zts-20121212/memcached-bare
--- a/support/build/extensions/no-debug-non-zts-20121212/memcached-bare
+++ b/support/build/extensions/no-debug-non-zts-20121212/memcached-bare
@@ -24,10 +24,38 @@ dep_manifest=${dep_package}_php-$series.composer.json
 
 echo "-----> Building ${dep_package}..."
 
+# can't build without this
+needed=( libsasl2-2 )
+missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
+if [[ "$missing" ]]; then
+    echo "Error! Missing libraries: $missing"
+    exit 1
+fi
+
+# let's see if libmemcached is there, if not then we have to use the vendored one
+needed=( libmemcached11 )
+missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
+if [[ "$missing" ]]; then
+    echo "Using vendored libmemcached..."
+    # use vendored libmcrypt
+    with_libmemcached_dir="--with-libmemcached-dir=${OUT_PREFIX}"
+else
+    echo "Using system libmemcached..."
+    # use system libmemcached
+    with_libmemcached_dir=
+    # but do we need headers?
+    needed=( libmemcached-dev )
+    missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
+    if [[ "$missing" ]]; then
+        apt-get update || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
+        apt-get install -y $missing
+    fi
+fi
+
 # we need libsasl2-dev for ext-memcached
 needed=( libsasl2-dev )
 missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
-if [[ -n "$missing" ]]; then
+if [[ "$missing" ]]; then
     apt-get update || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
     apt-get install -y $missing
 fi
@@ -38,7 +66,7 @@ pushd ${dep_dirname}
 phpize
 ./configure \
     --prefix=${OUT_PREFIX} \
-    --with-libmemcached-dir=${OUT_PREFIX}
+    ${with_libmemcached_dir}
 make -s -j 9
 # php was a build dep, and it's in $OUT_PREFIX. nuke that, then make install so all we're left with is the extension
 rm -rf ${OUT_PREFIX}/*
diff --git a/support/build/libraries/libmemcached b/support/build/libraries/libmemcached
--- a/support/build/libraries/libmemcached
+++ b/support/build/libraries/libmemcached
@@ -19,24 +19,38 @@ dep_archive_name=${dep_dirname}.tar.gz
 dep_url=https://launchpad.net/libmemcached/1.0/${dep_version}/+download/${dep_archive_name}
 dep_manifest=${dep_package}.composer.json
 
-# we need libsasl2-dev
-needed=( libsasl2-dev )
+# can't build without this
+needed=( libsasl2-2 )
 missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
-if [[ -n "$missing" ]]; then
-    apt-get update || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
-    apt-get install -y $missing
+if [[ "$missing" ]]; then
+    echo "Error! Missing libraries: $missing"
+    exit 1
 fi
 
-echo "-----> Building ${dep_package}..."
+# skip build if already present
+needed=( libmemcached11 )
+missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
+if [[ "$missing" ]]; then
+    # we need libsasl2-dev
+    needed=( libsasl2-dev )
+    missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
+    if [[ "$missing" ]]; then
+        apt-get update || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
+        apt-get install -y $missing
+    fi
+    echo "-----> Building ${dep_package}..."
 
-curl -L ${dep_url} | tar xz
-pushd ${dep_dirname}
-./configure --prefix=${OUT_PREFIX} --without-memcached --disable-static
-make -s -j 9
-make install-strip -s
-popd
+    curl -L ${dep_url} | tar xz
+    pushd ${dep_dirname}
+    ./configure --prefix=${OUT_PREFIX} --without-memcached --disable-static
+    make -s -j 9
+    make install-strip -s
+    popd
 
-rm -rf ${OUT_PREFIX}/share/man
+    rm -rf ${OUT_PREFIX}/share/man
+else
+    echo "-----> System ${dep_name} available, creating empty package..."
+fi
 
 python $(dirname $BASH_SOURCE)/../_util/include/manifest.py "heroku-sys-package" "heroku-sys/pkg-${dep_name}" "$dep_version" "${dep_formula}.tar.gz" > $dep_manifest
 
diff --git a/support/build/php b/support/build/php
--- a/support/build/php
+++ b/support/build/php
@@ -37,10 +37,21 @@ curl -L ${dep_url} | tar xz
 
 pushd ${dep_dirname}
 
-# we need libgmp-dev for GMP, libpam0g-dev for IMAP, libicu-dev for intl, libsasl2-dev for LDAP
+libicu="libicu55"
+if [[ $STACK == "cedar-14" ]]; then
+    libicu="libicu52"
+fi
+# we need libgmp for GMP, libpam0g for IMAP, libicu for intl, libsasl2/krb/ldap for LDAP
+needed=( libgmp10 libpam0g $libicu libsasl2-2 libkrb5-3 libldap-2.4-2 )
+missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
+if [[ "$missing" ]]; then
+    echo "Error! Missing libraries: $missing"
+    exit 1
+fi
+# we need libgmp-dev for GMP, libpam0g-dev for IMAP, libicu-dev for intl, libsasl2/krb5/ldap2-dev for LDAP
 needed=( libgmp-dev libpam0g-dev libicu-dev libsasl2-dev libkrb5-dev libldap2-dev )
 missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
-if [[ -n "$missing" ]]; then
+if [[ "$missing" ]]; then
     apt-get update || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
     apt-get install -y $missing
 fi
@@ -54,15 +65,35 @@ ln -s /usr/include/x86_64-linux-gnu/gmp.h /usr/include/gmp.h
 sed -i 's/LDAP_LIBDIR=$i\/$PHP_LIBDIR/LDAP_LIBDIR=$i\/$PHP_LIBDIR\/x86_64-linux-gnu/' configure
 sed -i 's/LDAP_SASL_LIBDIR=$LDAP_SASL_DIR\/$PHP_LIBDIR/LDAP_SASL_LIBDIR=$LDAP_SASL_DIR\/$PHP_LIBDIR\/x86_64-linux-gnu/' configure
 
+# let's see if mcrypt is there, if not then we have to use the vendored one
+needed=( libmcrypt4 )
+missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
+if [[ "$missing" ]]; then
+    echo "Using vendored libmcrypt..."
+    # use vendored libmcrypt
+    mcrypt_prefix="${OUT_PREFIX}"
+else
+    echo "Using system libmcrypt..."
+    # use system libmcrypt
+    mcrypt_prefix=
+    # but do we need headers?
+    needed=( libmcrypt-dev )
+    missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
+    if [[ "$missing" ]]; then
+        apt-get update || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
+        apt-get install -y $missing
+    fi
+fi
+
 configureopts=
 if [[ $dep_version == 7.* ]]; then
     configureopts="\
---with-mcrypt=shared,${OUT_PREFIX} \
+--with-mcrypt=shared${mcrypt_prefix:+","}${mcrypt_prefix} \
 --enable-opcache-file\
 "
 else
     configureopts="\
---with-mcrypt=${OUT_PREFIX} \
+--with-mcrypt${mcrypt_prefix:+"="}${mcrypt_prefix} \
 --with-mysql=shared \
 "
 fi
