only install missing Ubuntu packages if necessary

diff --git a/support/build/extensions/no-debug-non-zts-20121212/memcached-bare b/support/build/extensions/no-debug-non-zts-20121212/memcached-bare
--- a/support/build/extensions/no-debug-non-zts-20121212/memcached-bare
+++ b/support/build/extensions/no-debug-non-zts-20121212/memcached-bare
@@ -25,8 +25,12 @@ dep_manifest=${dep_package}_php-$series.composer.json
 echo "-----> Building ${dep_package}..."
 
 # we need libsasl2-dev for ext-memcached
-apt-get update || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
-apt-get install -y libsasl2-dev
+needed=( libsasl2-dev )
+missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
+if [[ -n "$missing" ]]; then
+    apt-get update || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
+    apt-get install -y $missing
+fi
 
 curl -L ${dep_url} | tar xz
 
diff --git a/support/build/libraries/libcassandra b/support/build/libraries/libcassandra
--- a/support/build/libraries/libcassandra
+++ b/support/build/libraries/libcassandra
@@ -20,8 +20,12 @@ dep_url=https://github.com/datastax/cpp-driver/archive/${dep_version}.tar.gz
 dep_manifest=${dep_package}.composer.json
 
 # we need libgmp-dev and cmake
-apt-get update || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
-apt-get install -y libgmp-dev cmake
+needed=( libgmp-dev cmake )
+missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
+if [[ -n "$missing" ]]; then
+    apt-get update || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
+    apt-get install -y $missing
+fi
 
 echo "-----> Building ${dep_package}..."
 
diff --git a/support/build/libraries/libmemcached b/support/build/libraries/libmemcached
--- a/support/build/libraries/libmemcached
+++ b/support/build/libraries/libmemcached
@@ -20,8 +20,12 @@ dep_url=https://launchpad.net/libmemcached/1.0/${dep_version}/+download/${dep_ar
 dep_manifest=${dep_package}.composer.json
 
 # we need libsasl2-dev
-apt-get update || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
-apt-get install -y libsasl2-dev
+needed=( libsasl2-dev )
+missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
+if [[ -n "$missing" ]]; then
+    apt-get update || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
+    apt-get install -y $missing
+fi
 
 echo "-----> Building ${dep_package}..."
 
