dynamically wait for newrelic-daemon to be up
instead of two seconds

diff --git a/support/build/extensions/no-debug-non-zts-20121212/newrelic b/support/build/extensions/no-debug-non-zts-20121212/newrelic
--- a/support/build/extensions/no-debug-non-zts-20121212/newrelic
+++ b/support/build/extensions/no-debug-non-zts-20121212/newrelic
@@ -68,12 +68,25 @@ fi
 # The daemon is a started in foreground mode so it will not daemonize
 # (i.e. disassociate from the controlling TTY and disappear into the
 # background).
+# we use the pidfile to wait for it to be up
+newrelic_pidfile=/tmp/newrelic-daemon.pid
 
 # daemon start
-/app/.heroku/php/bin/newrelic-daemon --watchdog-foreground --port "@newrelic-daemon" --logfile "/dev/stderr" --loglevel "${NEW_RELIC_DAEMON_LOG_LEVEL}" --pidfile "/tmp/newrelic-daemon.pid" &
+/app/.heroku/php/bin/newrelic-daemon --watchdog-foreground --port "@newrelic-daemon" --logfile "/dev/stderr" --loglevel "${NEW_RELIC_DAEMON_LOG_LEVEL}" --pidfile "$newrelic_pidfile" &
+newrelic_pid=$!
 
-# give it a moment to connect
-sleep 2
+# give it a moment to start up...
+while ! test -f "$newrelic_pidfile"; do
+	# ...unless it somehow crashes on start, then we have to bail to prevent an infite loop
+	if ! kill -0 $newrelic_pid 2> /dev/null; then # kill -0 checks if process exists
+		echo "Failed to start newrelic-daemon!" >&2
+		break;
+	fi
+	if [[ "$NEW_RELIC_DAEMON_LOG_LEVEL" == "info" || "$NEW_RELIC_DAEMON_LOG_LEVEL" == "debug" ]]; then
+		echo "Waiting for newrelic-daemon..." >&2
+	fi
+	sleep 0.1
+done
 EOF
 mkdir -p ${OUT_PREFIX}/etc/php/conf.d
 cat > ${OUT_PREFIX}/etc/php/conf.d/newrelic.ini-dist <<'EOF'
