use platform libsasl for libmemcached

diff --git a/support/build/libraries/libmemcached b/support/build/libraries/libmemcached
--- a/support/build/libraries/libmemcached
+++ b/support/build/libraries/libmemcached
@@ -14,25 +14,14 @@ dep_dirname=libmemcached-${dep_version}
 dep_archive_name=${dep_dirname}.tar.gz
 dep_url=https://launchpad.net/libmemcached/1.0/${dep_version}/+download/${dep_archive_name}
 
-# SASL Support.
-echo "-----> Building cyrus-sasl 2.1.26..."
-
-curl -LO ftp://ftp.cyrusimap.org/cyrus-sasl/cyrus-sasl-2.1.26.tar.gz
-# FTP doesn't play well with piping into tar xz
-tar xzf cyrus-sasl-2.1.26.tar.gz
-
-pushd cyrus-sasl-2.1.26
-./configure --prefix=${OUT_PREFIX} --with-plugindir=${OUT_PREFIX}lib/sasl2 --with-configdir=${OUT_PREFIX}lib/sasl2
-
-make -s -j 9
-make install -s
-popd
+# we need libsasl2-dev
+apt-get install -y libsasl2-dev || { echo "Failed to install libsasl2-dev; are you running this in a Docker build?"; exit 1; }
 
 echo "-----> Building libmemcached ${dep_version}..."
 
 curl -L ${dep_url} | tar xz
 pushd ${dep_dirname}
-CPPFLAGS=-I${OUT_PREFIX}/include LDFLAGS=-L${OUT_PREFIX}/lib ./configure --prefix=${OUT_PREFIX} --without-memcached
+./configure --prefix=${OUT_PREFIX} --without-memcached
 make -s -j 9
 make install -s
 popd
