Allow trying multiple download URLs for PHP builds
PHP 8.5 has two release managers, so it can be either managers' URL for a particular pre-release build.

diff --git a/support/build/php b/support/build/php
--- a/support/build/php
+++ b/support/build/php
@@ -33,7 +33,10 @@ dep_manifest=${dep_package}.composer.json
 
 echo "-----> Building ${dep_name} (${dep_version})..."
 
-curl -L ${dep_url} | tar xz
+for url in "${dep_url[@]}"; do
+	echo "Trying download from $url..."
+	curl -fL "${url}" | tar xz && break
+done || { echo "Download failed for ${dep_archive_name}"; exit 1; }
 
 pushd ${dep_dirname}
 
