Support heroku-24 in PHP builds and Hatchet tests
As always, the new stack gets the PHP version series with "active support" status as listed on https://www.php.net/supported-versions.php (heroku-22 was an exception, as the at-the-time-in-active-support-status PHP 8.0 did not support OpenSSL 3, so that stack only got PHP 8.1 support upon release).

GUS-W-14667548

diff --git a/support/build/php-min b/support/build/php-min
--- a/support/build/php-min
+++ b/support/build/php-min
@@ -24,6 +24,27 @@ curl -L ${dep_url} | tar xz
 
 pushd ${dep_dirname}
 
+# we need libreadline for PHP
+needed=()
+if [[ $STACK == heroku-2[02] ]]; then
+	needed+=( libreadline8 )
+else
+	needed+=( libreadline8t64 )
+fi
+missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
+if [[ "$missing" ]]; then
+	echo "Error! Missing libraries: $missing"
+	exit 1
+fi
+
+# we need libreadline-dev for PHP
+needed=( libreadline-dev )
+missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
+if [[ "$missing" ]]; then
+	apt-get update -qq || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
+	apt-get install -q -y $missing
+fi
+
 export PATH=${OUT_PREFIX}/bin:$PATH
 # cannot be built shared: date, ereg, opcache (always), pcre, reflection, sockets (?), spl, standard,
 # sqlite3 and pdo_sqlite are on by default but we're building them shared on purpose
