Add support for the Heroku-26 stack (#930)
This adds binary building and buildpack support for the upcoming
Heroku-26 stack based on Ubuntu 26.04.

In keeping with previous new stack additions, on the new stack the
buildpack will only support PHP versions that are currently in
"Active support" - so will only support PHP 8.4 and 8.5 (and then
further new versions as they are released):
https://www.php.net/supported-versions.php

The following Ubuntu 26.04 compatibility fixes landed in earlier PRs:

- Updating Apache's APR and APR-util library versions to resolve
  compilation errors with GCC 15:
  https://github.com/heroku/heroku-buildpack-php/pull/939
- Making the buildpack's `exit_trap()` implementation compatible with
  Bash 5.3: https://github.com/heroku/heroku-buildpack-php/pull/936

The following further issues are worked around in this PR:

- `ext-phalcon` fails to compile with GCC 15:
  https://github.com/heroku/heroku-buildpack-php/issues/927
  (for now we're just skipping building this package on Heroku-26)
- The `waitforit.sh` script breaks with the newly rewritten `coreutils`
  `tail` and `timeout` commands, so the test-only script has been
  updated to use the old GNU coreutils versions for now. See:
  https://github.com/heroku/heroku-buildpack-php/issues/931
- The ScoutAPM Hatchet test has to use PHP 8.3 (since ScoutAPM doesn't
  support newer PHP versions), which isn't available on the new stack,
  so that test has to be skipped on the new stack. See:
  https://github.com/scoutapp/scout-apm-php/issues/314

It wasn't possible to enable the buildpack's cgroups unit tests on
Ubuntu 26.04, since a GitHub Actions runner image for it doesn't yet
exist. Doing so is tracked at:
https://github.com/heroku/heroku-buildpack-php/issues/941

Note: This PR intentionally updates the Dev Center GHA workflow now
(which will mean it will add the Heroku-26 columns the next time there
is a release) - since it's fine if they show up slightly early, and will
mean one less thing to forget/coordinate later.

GUS-W-20775701.
GUS-W-20775708.

diff --git a/support/build/formulae/ext-phalcon b/support/build/formulae/ext-phalcon
--- a/support/build/formulae/ext-phalcon
+++ b/support/build/formulae/ext-phalcon
@@ -2,4 +2,11 @@
 
 dep_name=$(basename "$BASH_SOURCE")
 
+# ext-phalcon fails to compile when using GCC 14+, so can't currently be built on Heroku-26+:
+# https://github.com/heroku/heroku-buildpack-php/issues/927
+if [[ $STACK != +(heroku-22|heroku-24) ]]; then
+	echo "Version not supported on stack ${STACK}, skipping."
+	exit 9
+fi
+
 source "$(dirname "$BASH_SOURCE")/include/pecl-ext"
