Auto-update Dev Center article via API after sync
Finds the start and end markers from the generated sections and produces an 'ed' format patch, then updates (or, on dry-run or if checkbox disabled, validates) the article using the Dev Center API.

GUS-W-9364734

diff --git a/.github/workflows/platform-sync.yml b/.github/workflows/platform-sync.yml
--- a/.github/workflows/platform-sync.yml
+++ b/.github/workflows/platform-sync.yml
@@ -3,6 +3,8 @@ run-name: Sync${{ inputs.dry-run == true && ' dry-run' || '' }} from dist-$STACK
 
 env:
   stacks_list_for_shell_expansion: "{heroku-20,heroku-22,heroku-24-amd64,heroku-24-arm64}"
+  src_path_suffix: "-develop/"
+  dst_path_suffix: "-stable/"
 
 on:
   workflow_dispatch:
@@ -31,6 +33,11 @@ on:
         description: 'Only list package changes, without syncing'
         type: boolean
         default: false
+        required: false
+      update-devcenter:
+        description: 'Update "PHP Support" Dev Center article after sync'
+        type: boolean
+        default: true
         required: false
 
 permissions:
@@ -103,7 +110,7 @@ jobs:
           # yes gets "n" to print for dry-runs so the sync aborts
           # errors are redirected to /dev/null, and we || true, to suppress SIGPIPE errors from 'docker run' exiting eventually
           # we need -i for Docker to accept input on stdin, but must not use -t for the pipeline to work
-          (yes "${{ inputs.dry-run == true && 'n' || 'y' }}" 2>/dev/null || true) | docker run --rm -i --env-file=support/build/_docker/env.default heroku-php-build-${{matrix.stack}}:${{github.sha}} sync.sh lang-php dist-${{matrix.stack}}-stable/ 2>&1 | tee sync-${{matrix.stack}}.log
+          (yes "${{ inputs.dry-run == true && 'n' || 'y' }}" 2>/dev/null || true) | docker run --rm -i --env-file=support/build/_docker/env.default heroku-php-build-${{matrix.stack}}:${{github.sha}} sync.sh lang-php dist-${{matrix.stack}}${{env.dst_path_suffix}} 2>&1 | tee sync-${{matrix.stack}}.log
       - name: Upload sync log as artifact
         uses: actions/upload-artifact@v4
         with:
@@ -127,6 +134,8 @@ jobs:
   devcenter-generate:
     needs: sync
     runs-on: ubuntu-22.04
+    outputs:
+      diff_result: ${{ steps.diff.outputs.diff_result }}
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -145,7 +154,7 @@ jobs:
       - name: Generate Dev Center article sections
         run: |
           set -o pipefail
-          urls=( https://lang-php.s3.amazonaws.com/dist-${{ env.stacks_list_for_shell_expansion }}-${{ inputs.dry-run == true && 'develop' || 'stable' }}/packages.json )
+          urls=( https://lang-php.s3.amazonaws.com/dist-${{ env.stacks_list_for_shell_expansion }}${{ inputs.dry-run == true && env.src_path_suffix || env.dst_path_suffix }}packages.json )
           # generate.php can generate individual sections, but doing it in one go a) is faster and b) means this code does not need to know what those sections are
           # Instead we split the generated contents into individual files, with the known delimiter as the split pattern.
           # tee stderr to a file
@@ -165,11 +174,11 @@ jobs:
         run: |
           set -o pipefail
           # jq -j, not -r, otherwise we get a stray trailing newline
-          curl -H "Accept: application/json" https://devcenter.heroku.com/api/v1/articles/2021 | jq -j '.content' > php-support.md
+          curl -H "Accept: application/json" https://devcenter.heroku.com/api/v1/articles/php-support | jq -j '.content' > php-support.md
           # Because the articles are edited in a web interface, they likely use CRLF line endings.
           # We will be patching using the LF line ending section files generated in an earlier step.
           # For this reason, we may have to convert to LF, so we check if the file would be converted by dos2unix using the --info option.
-          # The "c" info flag prints only file names that would trigger conversion; we first remember this output for the next step via tee -a.
+          # The "c" info flag prints only file names that would trigger conversion; we first remember this output for the next step via tee.
           # The "0" flag triggers zero-byte output for happy consumption by xargs
           # Then, we finally run the conversion (if needed) by passing the file name to dos2unix again via xargs.
           dos2unix --info=c0 php-support.md | tee have_crlf.txt | xargs -r0 dos2unix
@@ -184,11 +193,11 @@ jobs:
             last=$(tail -n1 "$f")
             # grep the line numbers (-n) as fixed (-F) full-line (-x) strings and extract them
             start=$(set -o pipefail; grep -nFx "$first" php-support.md | cut -d':' -f1) || {
-              echo "::warning title=Failed to match section start marker::Start marker '$first' not found in input markdown; skipping section..."
+              echo "::warning title=Failed to match section start marker::Start marker '$first' not found in input markdown; skipping '$f'..."
               continue
             }
             end=$(set -o pipefail; grep -nFx "$last" php-support.md | cut -d':' -f1) || {
-              echo "::warning title=Failed to match section end marker::End marker '$last' not found in input markdown; skipping section..."
+              echo "::warning title=Failed to match section end marker::End marker '$last' not found in input markdown; skipping '$f'..."
               continue
             }
             # write out a line with the start-end range and filename
@@ -240,17 +249,75 @@ jobs:
             cat php-support.diff >> "$GITHUB_STEP_SUMMARY"
             echo '``````' >> "$GITHUB_STEP_SUMMARY" # six instead of three backticks because our output is likely to also contain series of backticks
           }
-      - name: Output complete Dev Center article markdown
+      - name: Upload diff as artifact
         if: steps.find-section-markers.outputs.num_sections > 0 && steps.diff.outputs.diff_result == 1
+        uses: actions/upload-artifact@v4
+        with:
+          name: devcenter-diff
+          path: |
+            have_crlf.txt
+            php-support.diff
+  devcenter-update:
+    needs: devcenter-generate
+    if: ${{ needs.devcenter-generate.outputs.diff_result == 1 }}
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Install dos2unix
+        run: |
+          sudo apt-get update
+          sudo apt-get install dos2unix
+      - name: Download current Dev Center article markdown
         run: |
           set -o pipefail
-          echo '## Updated markdown for ["PHP Support" Dev Center article](https://devcenter.heroku.com/articles/php-support)' >> "$GITHUB_STEP_SUMMARY"
-          echo "${{ inputs.dry-run == true && '**This is based on the source bucket (due to dry-run mode)**, not the production bucket.' || '-n' }}" >> "$GITHUB_STEP_SUMMARY"
-          echo '``````markdown' >> "$GITHUB_STEP_SUMMARY" # six instead of three backticks because our output is likely to also contain series of backticks
+          # we need to query this JSON twice, and a temp file is easiest for error handling
+          curl -H "Accept: application/json" https://devcenter.heroku.com/api/v1/articles/php-support > php-support.json
+          # jq -j, not -r, otherwise we get a stray trailing newline
+          cat php-support.json | jq -je '.content' > php-support.md
+          # here we want the trailing newline; run through alternative operator and empty filter to cause exit status 4 with -e if field missing
+          cat php-support.json | jq -re '.id // empty | @sh "article_id=\(.)"' >> "$GITHUB_ENV"
+          # Because the articles are edited in a web interface, they likely use CRLF line endings.
+          # We will be patching using an LF diff.
+          # For this reason, we may have to convert to LF, so we check if the file would be converted by dos2unix using the --info option.
+          # The "c" info flag prints only file names that would trigger conversion; we first remember this output for the next step via tee -a.
+          # The "0" flag triggers zero-byte output for happy consumption by xargs
+          # Then, we finally run the conversion (if needed) by passing the file name to dos2unix again via xargs.
+          dos2unix --info=c0 php-support.md | tee have_crlf.txt | xargs -r0 dos2unix
+      - name: Download diff artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: devcenter-diff
+          path: devcenter-diffs
+      - name: Patch Dev Center article markdown
+        run: |
+          patch php-support.md devcenter-diffs/php-support.diff
           # convert back to the original CRLF if dos2unix ran in an earlier step (have_crlf.txt will be empty if not, and xargs will not run due to -r)
           cat have_crlf.txt | xargs -r0 unix2dos
+      - name: Validate Dev Center article
+        if: inputs.dry-run == true || inputs.update-devcenter == false
+        run: |
+          set -o pipefail
+          curl -sS --fail-with-body -X POST -K <(echo -n "user = bot:"; printenv "HEROKU_DEVCENTER_API_TOKEN") -H "Accept: application/json" --data-urlencode 'article[content]@php-support.md' "https://devcenter.heroku.com/api/v1/private/articles/${article_id}/validate.json"
+      - name: Output Dev Center article
+        if: inputs.dry-run == true || inputs.update-devcenter == false
+        run: |
+          echo '## Updated markdown for ["PHP Support" Dev Center article](https://devcenter.heroku.com/articles/php-support)' >> "$GITHUB_STEP_SUMMARY"
+          echo "${{ inputs.dry-run == true && '> [!IMPORTANT]' || '-n' }}" >> "$GITHUB_STEP_SUMMARY"
+          echo "${{ inputs.dry-run == true && '**This is based on the source bucket (due to dry-run mode)**, not the production bucket.' || '-n' }}" >> "$GITHUB_STEP_SUMMARY"
+          echo "${{ inputs.dry-run == true && '' || '-n' }}" >> "$GITHUB_STEP_SUMMARY"
+          echo "> [!WARNING]" >> "$GITHUB_STEP_SUMMARY"
+          echo "> **Dev Center has not been updated with the contents below**, the output is for reference only" >> "$GITHUB_STEP_SUMMARY"
+          echo >> "$GITHUB_STEP_SUMMARY"
+          echo '``````markdown' >> "$GITHUB_STEP_SUMMARY" # six instead of three backticks because our output is likely to also contain series of backticks
           cat php-support.md >> "$GITHUB_STEP_SUMMARY"
           echo '``````' >> "$GITHUB_STEP_SUMMARY" # six instead of three backticks because our output is likely to also contain series of backticks
+      - name: Update Dev Center article
+        if: inputs.dry-run == false && inputs.update-devcenter == true
+        run: |
+          set -o pipefail
+          curl -sS --fail-with-body -X PUT -K <(echo -n "user = bot:"; printenv "HEROKU_DEVCENTER_API_TOKEN") -H "Accept: application/json" --data-urlencode 'article[content]@php-support.md' "https://devcenter.heroku.com/api/v1/private/articles/${article_id}.json"
+          echo 'Successfully updated ["PHP Support" Dev Center article](https://devcenter.heroku.com/articles/php-support) with synced packages.' >> "$GITHUB_STEP_SUMMARY"
   changelog-generate:
     needs: sync
     runs-on: ubuntu-22.04
